---
title: 'Anders kijken naar bodems'
date: 2023-10-28
author: Jan Bokhorst
---

 Niet teveel vanuit voorstellingen naar de bodem kijken maar de eigen ervaring centraal stellen. Daar gaat dit del van de website over.


De landbouw is veranderd. Voorheen werd van ouders op kinderen overgedragen hoe de bodem bewerkt moest worden, hoe te zaaien, te oogsten, enzovoort. Het ging dan niet alleen om kennis, maar om een algehele houding rond hoe de dingen te doen.  

Toen kwam er een nieuwe kijk op de landbouw. De kalk en de kunstmest kwamen onder meer. Voor de hoeveelheden had men geen gevoel. De voorlichter vertelde wel hoeveel nodig was. Steeds meer dingen in de landbouw kwamen van elders. ‘Onderzoek heeft uitgewezen…….’. De verhouding tot de landbouw werd afstandelijker. Er ontstond een angst om zelf te kijken en beslissingen te nemen. Er kwamen problemen rond milieu en plantenziekten, er kwamen regels. Gek genoeg waren het de problemen rond die regels die aanleiding waren om toch weer meer te gaan kijken en zelf te beslissen. Dat meer zelf kijken en beslissen gebeurde in de gangbare landbouw, maar niet bij iedereen, want het kon soms ook zonder. Het gebeurt in de biologische landbouw sowieso omdat er intensief met de natuur samengewerkt moet worden. Een akkerbouwer die van gangbaar naar biologisch was omgeschakeld zei laatst: ik ben in een andere wereld terecht gekomen.De gangbare wetenschapper verliest, wanneer hij voor een strikt intellectuele aanpak kiest, vaak het vermogen om de betekenis van ontwikkelingen in te zien, om samenhangen te zien. Om zich bijvoorbeeld in te leven in dat wat voor de regenworm belangrijk is. Met een strikt intellectuele aanpak kun je geen landbouw bedrijven. Een boer die alleen maatregelen toepast waarvan de werking wetenschappelijk significant is aangetoond, is snel failliet.Voor goed bodembeheer moet je anders gaan kijken en je inleven in wat je ziet. Dit is de grondgedachte bij de meeste teksten in dit onderdeel van de website. Het zijn probeersels. Graag commentaar.


