---
title: 'Beworteling'
date: 2023-10-28
author: Jan Bokhorst
---



Een belangrijk onderdeel van de bodembeoordeling is de beoordeling van de beworteling. De bodemprocessen zijn vooral van belang in dat deel van de grond waar wortels toegang toe hebben.


**Beworteling**  

Aan de wortels kun je zien wat een plant van de bodem vindt. Zelden zijn er geen problemen met de structuur. Neem de juiste maatregelen.   
Wortels nemen water en voedingsstoffen op en vooral voor de opname van voedingsstoffen is energie nodig. De energie in de vorm van koolhydraten komt uit de bovengrondse delen, de zuurstof komt uit de bodem. Alleen de actieve punt van de wortels neemt water en voedingsstoffen op en doet dit gedurende enkele dagen. Wortels moeten dus steeds door kunnen groeien. Wortelsterfte treedt op bijvoorbeeld bij droogte en bij maaien en weiden van grasland.  

**Eisen aan de bodem**

Groeiruimte, vocht, voedingsstoffen en vooral lucht moeten voldoende beschikbaar zijn.  

**Groeiruimte**

Wortels kunnen dichte grond of een storende laag niet opheffen. Er moeten poriën in de bodem zijn om te kunnen groeien. Bij de meeste planten moeten deze poriën groter zijn dan 0,2 mm. Sommige plantenwortels (zonnebloemen, vlas, klaver) hebben poriën van 0,3 tot 0,5 mm nodig. Wortels kunnen wel kleine poriën (0,2 mm) ingroeien en deze vergroten. Hierbij kan een druk ontstaan van 5 tot 24 atmosfeer. Bij een losse grond zijn er veel en vrij dunne wortels, bij een verdichte grond worden de wortels dikker, zijn schaars en laten veel bochten zien met hier en daar een vaak kronkelig zijworteltje. De vorm van de wortels geeft dus al verdichting aan.  

**Vocht en voedingsstoffen**

Wanneer de grond droger wordt, wordt niet alleen de wateropname moeilijker maar ook de opname van voedingsstoffen. De voedingsstoffen bevinden zich in de vochtige kluiten. Bij droogte neemt de verkurking van de wortels toe waardoor het deel van de wortels dat water en voedingstoffen opneemt ook kleiner wordt. Stikstof, fosfor en de zuurgraad hebben veel invloed op de wortelontwikkeling. Wortels groeien vaak heel gericht naar bepaalde concentraties aan stikstof of fosfor.  
Wanneer in diepere lagen van de bodem meer stikstof, fosfor of kalk aanwezig is, bijvoorbeeld stikstof in de veenlaag bij klei op veen, dan hebben de wortels de neiging om zich daar te ontwikkelen mits er zich geen storende laag boven deze laag bevindt.  

**Organische stof**

Organische stof heeft een sterke invloed op de wortelontwikkeling. Een bouwvoor met een hoog organischestofgehalte laat een intensievere beworteling zien dan bij lagere gehalten aan organische stof, ook al is de bodemstructuur dezelfde. Bij veengronden met een goede bodemstructuur geven alle gewassen dus een veel intensievere beworteling. De wortelharen nemen ook toe.  

**Zuurstof en koolzuur**

De wortel heeft zuurstof nodig. De koolzuur die hierbij gevormd wordt, moet worden afgevoerd. Het zuurstofgehalte van de grond is niet zo belangrijk. Veel belangrijker is de snelheid van aanvoer. Deze is groter wanneer de poriën in verbinding staan met de bovengrond. Slempgevoelige gronden moeten daarom vaak opengeschoffeld worden. Wormen die zichtbare poriën in de bovengrond maken dragen bij aan de aanvoer van zuurstof.Een grond met een kruimelige structuur en voldoende hoog organischestofgehalte levert de beste voorwaarde voor een goede wortelontwikkeling. Snel opwarmen in het voorjaar is van belang. Dit gaat sneller wanneer de grond minder water en meer humus en lucht bevat.  

**Praktijkmaatregelen**  

**Voeding**

Bij bodems met een lage voedingstoestand is de invloed van voedingsstoffen op de beworteling goed merkbaar. Van de voedingsstoffen is fosfor degene die de wortelgroei het meest stimuleert. In mindere mate geldt dit voor stikstof. Bij weinig stikstof stimuleert een stikstofbemesting de wortelgroei. Bij een ruime stikstofvoorzienig neemt de wortelgroei af met een extra stikstofbemesting. Kalium daarentegen heeft geen invloed op de beworteling.Bekalken kan de wortelgroei ook stimuleren bij een lage zuurgraad. Stalmest en compost stimuleren de beworteling. Verhoging van het organischestofgehalte heeft een positieve invloed op het poriënvolume en het vochtvasthoudend vermogen van de bodem en zo een positief effect op de beworteling.  

**Bodembewerking**

Bij storende lagen kan een diepe bodembewerking de beworteling stimuleren. Deze bewerking moet dan onder droge omstandigheden van de ondergrond plaatsvinden. Na deze bewerking moet een gewas met zijn wortels de ontstane ruimte in de bodem innemen. Verslempte gronden moeten tijdens de teelt mechanisch open geschoffeld worden.  

**Waterhuishouding**

Een goede waterafvoer zorgt voor een bodem waarin beworteling kan plaatsvinden. Daarom is het op de meeste gronden aan te bevelen om de grondwaterstand zo laag mogelijk te houden. Dit geldt niet voor droogtegevoelige zandgronden.  

**Keuze gewas en vruchtopvolging**

Elk gewas heeft een andere soort beworteling. Intensief wortelende gewassen zijn granen en grassen, terwijl sla en spinazie juist een veel mindere beworteling laten zien. Afhankelijk van de situatie kan specifiek voor een bepaald gewas gekozen worden. Bijvoorbeeld op zandgronden onder grasland kan een teelt van granen een sterk bodemverbeterend effect hebben.Het telen van verschillende gewassen in een vruchtopvolging heeft door de verschillende bewortelingstypen een positief effect op de bodemkwaliteit.








