---
title: 'Bodem en klimaat'
date: 2023-10-28
author: Jan Bokhorst
---


De bodem is belangrijk in het kader van de klimaatproblematiek. Het gaat dan niet zozeer om veel koolstof in de grond in te brengen, maar vooral om de bodemkwaliteit te verbeteren


**Bodem en klimaat**  

Vaak wordt gedacht dat koolstof afkomstig van plantenresten in de grond brengen belangrijk is in het kader van de klimaatproblematiek. Men vergeet dan dat de ingebrachte koolstof door het bodemleven weer wordt omgezet in koolzuur en in de atmosfeer terugkomt. Hierdoor is op wat langere termijn gezien het effect bijna nul.  
 **Waarom koolstof in de grond brengen niet zo veel kan bijdragen**-Wanneer je organische stof in de bodem brengt wordt het dus door het bodemleven weer afgebroken en komt de koolzuur weer in de atmosfeer terecht. Na ca. 40 jaar is alle koolstof die in de grond is gebracht weer in de atmosfeer.  
(Kijk maar eens naar bossen in natuurgebieden waar al duizenden jaren blad en dode wortels in de grond komen. In de bodems onder die bossen bevindt zich niet zoveel koolstof. Bij veen is dat wel heel anders).  
-Wanneer je een nieuw plan bedenkt met meer gewassen die organische stof in de bodem brengen zoals meer granen en grassen en je gebruikt regelmatig compost en dat hou je vele jaren vol dan is dat toch maar een eenmalige actie.(Je brengt bijvoorbeeld ieder jaar twee keer zoveel koolstof in de grond. Die hoeveelheid moet je na 10 jaar door 10 delen, na 100 jaar door 100 en op lange termijn wordt de bijdrage bijna 0. De koolstof die via menselijke activiteiten in de atmosfeer komt is niet eenmalig, maar gaat jaar in jaar uit door. Verder is er niet zoveel compost beschikbaar).  
Wat wel kan bijdragen: minder koolstof in de vorm van koolzuur naar de atmosfeer laten ontsnappen  
-Nu komt bodemvruchtbaarheid om de hoek kijken. Bodemvruchtbaarheid betekent een hogere opbrengst en een hogere meststofefficiëntie. Bij bodemvruchtbaarheid gaat het niet in eerste instantie om veel koolstof in de grond te brengen. Het gaat om een evenwicht in aanvoer van stikstofrijk en koolstofrijk voer voor het bodemleven.(Bijvoorbeeld:heel mooi is gras/klaver. Je hebt koolstofrijke graswortels, stikstofrijke klaver en het resultaat is veel wormen en stikstof die geen fossiele brandstof nog had.of drijfmest (stikstofrijk) in de nazomer op een koolstofrijke groenbemester uitbrengen.ofstalmest gebruiken: mengsel van stikstofrijke mest en koolstofrijk stro).   
Let op:  
Veel organische stof in de bodem betekent ook veel stikstof in de organische stof (stikstof is energie bij kunstmest of landoppervlakte bij vlinderbloemigenteelt) en veel fosfor in de organische stof (fosforschaarste). De verhouding C:N:P in organische stof is ca 100:10:1)  
Wat nog meer doen  
Koolstof onder de bewerkte laag inbrengen – Niet kerende grondbewerking – De hele keten aanpakken (ca 25% van de koolzuuruitstoot van de menselijke activiteit op de wereld komt van de voedselproductie; slechts 30% van deze 25% komt van de teelt zelf) – vertering van veen beperken - enz. enz.    
Het Parijse akkoord  
Er is al eerder op gewezen dat er een fout in het Parijse akkoord zit. Iederjaar 0,4% organische stof erbij. Ook hier lijkt vergeten dat er organische stof afgebroken wordt. Vergelijk het met een emmer met een gat erin. Je doet iedere keer een bepaalde hoeveelheid water in de emmer en er onstaat een bepaald niveau. Nu wil je een hoger niveau. Dan moet je meer water steeds in de emmer doen. Wanneer je jaarlijks meer organische stof wilt hebben dan moet je jaarlijks meer geven en op een gegeven moment is er geen ruimte meer voor voedselproductie. Bij de bodem is het gat de afbraak van organische stof door het bodemleven.   
Een addertje onder het gras?  
Er zijn dingen die over het hoofd gezien worden? Veranderingen van golfstromen door smelten van ijs op noordpool? Extreem ingrijpen op korte termijn is van belang? Alle beetjes helpen?  
Studies die aangeven dat koolstof in de bodem brengen in de landbouw niet zoveel kan bijdragen aan koolstofvastlegging:  

**Biologisch** Muller, e.a., 2016. Organic farming, climate change mitigation and beyond. www.ifoam-eu.org.  

**EU** Berge, H. ten e.a.. 2017. Research for Agri Committee. Preserving agricultural soils in the EU. http://www.europarl.europa.eu/committees/en/supporting-analyses-search.html 

**20 gebieden gehele wereld**  
Minasny, B. e.a., 2017. Soil carbon 4 per mille. Geoderma, Vol 292, p 59-86. https://doi.org/10.1016/j. geoderma.2017.01.002  




