---
title: 'Bodem en voedingsstoffen'
date: 2023-10-28
author: Jan Bokhorst
---


Een korte beschrijving van de belangrijkste voedingsstoffen voor de plant in de bodem.


**Bodem en voedingsstoffen**   

De verschillende voedingsstoffen hebben steeds weer een heel ander gedrag in de bodem. Bij sommige (stikstof, fosfor, zwavel en veel sporenelementen) bepaalt het bodemleven sterk de beschikbaarheid.   



**Stikstof**

Stikstof is in gesteenten maar zeer beperkt aanwezig, maar in de atmosfeer in grote hoeveelheden. Boven elke hectare bevindt zich 85000 ton stikstof. In een bodem met 25% lucht bevindt zich in de bovenste 50 cm 1250 kg stikstof per ha. Wil stikstof beschikbaar zijn voor plant en humus, dan moet het gebonden worden. Micro-organismen die in symbiose leven met planten zijn de belangrijkste bron van gebonden stikstof. De industriematige binding van stikstof bij de kunstmestfabricage komt op de tweede plaats.  
Wanneer de plantenresten die stikstof bevatten in de bodem komen, worden ze omgezet en komt er in eerste instantie ammonium uit vrij (NH4+). Onder luchtarme omstandigheden en bij een pH boven 7 kan deze ammonium als ammoniak (NH3) weer de lucht in gaan. De ammonium wordt ook aan humus en klei geboden (geadsorbeerd). Onder zuurstofrijke omstandigheden wordt de ammonium omgezet in nitraat (NO3-). Deze nitraat kan door de plant opgenomen worden, maar kan ook uitspoelen. Verder kan deze nitraat onder luchtarme omstandigheden gereduceerd worden tot NO2- en N2O (lachgas). Dit lachgas kan naar de atmosfeer ontwijken. De stikstof die in de plantenresten achterblijft wordt geleidelijk omgezet in humus, waarin de stikstof in een stabiele vorm aanwezig is.  
De stikstofhuishouding is gezien de vele vormen waarin deze voorkomt en de overgang van de ene vorm in de andere zeer ingewikkeld. Hoewel stikstof voor de plant zeer belangrijk is, is er in het verleden nooit een bodemanalyse geweest die de stikstofbemesting begeleidde. Bij een aantal intensieve teelten wordt de nitraatbepaling als indicatie voor bijbemesting gebruikt. Verder wordt het per bodemtype gecorrigeerde totaal gehalte aan stikstof gebruikt (NLV). De processen zijn echter zo ingewikkeld, dat dit slechts een zeer globale hulp is. Modellering van het bodemleven op het gebied van stikstofvrijmaking wordt ook toegepast. Hoewel ook dit globaal is, geeft het toch inzicht in de dynamiek. Het is vooral een hulpmiddel om processen op het spoor te komen die op een bepaald moment het belangrijkste zijn. Het model NDICEA (www.NDICEA.nl) is in Nederland het best uitgetest en meest gebruikt. Lees hier meer over stikstof.  
**Fosfor**Planten kunnen fosfor opnemen, nadat dit vrijkomt uit organische en minerale verbindingen. Planten werken actief mee aan dit proces. Maar als fosfor vrijkomt in de bodem, dan wordt het vastgelegd aan voornamelijk calcium, ijzer en aluminium. Hierdoor is fosfor zeer weinig in de bodemoplossing aanwezig. Deze slechte oplosbaarheid bepaalt het hele beheer van fosfor.  
Planten kunnen op vele manieren fosfor vrijmaken:  
-meer wortels vormen;-diepere wortels vormen;-stoffen (exudaten), die vaak zuur zijn, uitscheiden die fosfor vrijmaken;-enzymen uitscheiden (bijv. fytaat) die fosfor vrijmaken;-voeding uitscheiden voor micro-organismen om ze te stimuleren fosfor te vrijmaken;-een verbinding aangaan met schimmels die actief fosfor voor de plant opnemen (mycorrhiza).  
Fosfor komt in verschillende vormen in de bodem voor:-gebonden (geadsorbeerd) aan positief geladen bodemdeeltjes (organische stof en kleideeltjes);-in de vorm van minerale verbindingen (aluminiumfosfaten, ijzerfosfaten en calciumfosfaten);-in de vorm van organische verbindingen (fosfaat mono-esters (vooral fytaat), di-esters en fosfonaten).  
De verdeling van de verschillende fosfaatvormen in een grond kan gemeten worden met de methode van Chang en Jackson (1958).  
Er zijn veel verschillende analysemethoden om de voor de plant beschikbare bodemfosfor te meten. In de EU zijn er nu 27 in gebruik. Dat geeft al aan dat het moeilijk is om de fosforbeschikbaarheid middels een analyse te bepalen. Vaak wordt gekozen voor een combinatie van makkelijk en moeilijk te extraheren methodes. Veel gebruikte extractiemethoden voor beschikbaar bodemfosfor zijn P-PAE, Spurway-analyse, Pw, P-Olsen en P-Al. Het probleem met de beoordeling van de resultaten van het gebruik van deze extractiemethoden is dat ze allen worden uitgevoerd aan de gehele bodem. Ze houden geen rekening met beworteling, bodemcompactie of mineralisatie uit organisch fosfor en met de vele andere methoden van de plant om fosfor op te nemen. De grond bijvoorbeeld een uur schudden met een zoutextract kan nooit datgene nabootsen wat zich gedurende een heel groeiseizoen in de bodem afspeelt aan chemische en biologische processen. Verder speelt ook een rol dat alleen de fosfor binnen 1 tot 2 mm van de actieve wortel beschikbaar is. De bodemanalyse analyseert alle grond, maar dan weer niet de grond onder de bouwvoor en die kan ook een belangrijke rol in de fosforvoorziening innemen.  
Gezien het gedrag van fosfor in de grond wordt al langer voor een combinatie van makkelijk en moeilijk extraheerbaar fosfor gekozen. De fruitteelt in Nederland gebruikt de combinatie Pw-getal en P-Al. Koch-Eurolab gebruikt ook al langer meerdere analysemethoden. Het Louis Bolk Instituut (later voortgezet door Gaia Bodemonderzoek) startte in 1981 met de combinatie van Pw-getal en P 8M HCl. Het Blgg gebruikt sinds enkele jaren de combinatie van P-CaCl2 en P-Al. Ook dit is een combinatie van een licht en een sterk extractiemiddel, maar P-CaCl2 extraheert maar zeer weinig fosfor en draagt maar beperkt bij aan inzicht in de fosforsituatie.**Kalium**Kalium onderscheidt zich van stikstof en fosfor omdat het soms in aanzienlijke hoeveelheden in niet verweerde mineralen aanwezig is en ook omdat kalium niet in organisch gebonden vorm in de bodem voorkomt. Verder bindt kalium zich aan humus en klei op een wijze waarop uitwisseling met andere elementen mogelijk is. Zo is deze ‘geadsorbeerde’ kalium toch voor de plant beschikbaar. Deze mogelijkheid van adsorptie uit zich bijvoorbeeld in het volgende: wanneer er water door een grond zakt, spoelt er vrijwel geen kalium uit, maar wanneer er een zoutoplossing door de grond zakt, spoelt er wel kalium uit.Op jonge kalkrijke gronden bevindt kalium zich in veldspaten en glimmers (mica’s). Hieruit komt het door verwering vrij. Wanneer een duinzandgrond in de zon glinstert, dan bevat deze dus glimmers en ook verweerbare kalium. Met die verwering van mineralen moet rekening gehouden worden. Op de voormalige OBS-bedrijven in Nagele in de Noordoostpolder vond in de 80-er jaren van de vorige eeuw vergelijkend onderzoek plaats tussen een biologisch-dynamisch bedrijf en een gangbaar bedrijf. Op het biologisch-dynamische bedrijf was een duidelijk tekort aan kalium op de mineralenbalans, op het gangbare een overschot. Toch was het kaliumgehalte in de bodem (K-HCl) na verloop van jaren op beide bedrijven gelijk. Dit wijst op de rol van bodemleven bij de kaliumhuishouding. Ook een intensievere beworteling kan een rol spelen (Verma, 1963).  
Het naleverend vermogen van kalium is in te schatten door extractie met 8N HCl. Dit werd door het Louis Bolk Instituut en Gaia Bodemonderzoek altijd standaard gedaan en vele malen kon worden aangetoond dat de naleverbare kalium toenam na jarenlang gebruik van bijvoorbeeld stalmest. De ervaringen op proefboerderij OBS, op andere proefvelden en bij bedrijfsanalyses wijzen erop dat bodemleven, beworteling en kaliumbeschikbaarheid toch niet los van elkaar zijn te zien.  
Het spreekt voor zich dat op de oudere (dek)zandgronden nalevering van kalium geen rol speelt. De vaak eenzijdige koolstofrijke humus op deze gronden draagt weinig bij aan de levensprocessen in de bodem, maar bindt kalium wel sterk.  
Zware kalkarme kleigronden fixeren toegediende kalium sterk. Praktijkervaringen wijzen erop dat een actieve levende bodem dit proces afremt, maar onderzoek in deze richting is niet bekend.**Magnesium**Magnesium bindt zich aan humus en kleideeltjes in de grond. De hoeveelheid magnesium aan dit adsorptiecomplex wordt beïnvloed door calcium, kalium en waterstof. Verder speelt het vochtgehalte van de grond een rol. Onder natte omstandigheden gaat kalium meer in oplossing en bindt magnesium zich sterker aan humus en klei. Magnesiumgebrek komt daarom meer voor in natte zomers.Op zure grond wordt magnesium door waterstof van het adsorptiecomplex verdreven. Door te bekalken verdwijnt de waterstof en kan er meer magnesium gebonden worden en treedt minder snel magnesiumgebrek op.  
Kopziekte komt bij rundvee voor als er teveel kalium in het voer zit. Deze ziekte treedt evenwel minder op bij een lage K/Mg verhouding in de grond. Magnesiumbemesting kan daardoor kopziekte beperken.  
Teveel magnesium aan het adsorptiecomplex geeft enerzijds een minder goede bodemstructuur omdat magnesium sterk water bindt, anderzijds remt veel magnesium de opname van calcium.  
**Calcium**Calciumgebrek kan sporadisch voorkomen bij landbouwgewassen, maar de invloed van calcium op de bodemstructuur is veel belangrijker om rekening mee te houden. Die invloed heeft meerdere kanten:  
1. Humus en klei zijn negatief geladen, stoten elkaar af en vertonen daarom weinig samenhang. Ook de kleideeltjes onderling stoten elkaar af. Calcium dat positief geladen is, vormt een brug en verbetert zo de samenhang en de structuur. Calcium doet dit beter dan andere positief geladen elementen.  
2.Calcium verdringt natrium van het adsorptiecomplex. Natrium bindt veel water en heeft een negatieve invloed op de structuur. Na verdringing door calcium spoelt natrium uit. De werking van calcium is het sterkst als calcium in de vorm van gips wordt gegeven. Gips is calciumsulfaat en de natrium spoelt als natriumsulfaat uit.  
3.Calcium, indien gegeven in de vorm van kalk, verhoogt de pH-waarde van de grond. Wanneer zo een neutrale grond wordt bereikt, verhoogt dit de activiteit van bacteriën sterker dan die van schimmels. Bacteriën vormen kitstoffen en bevorderen daarmee aggregaatvorming en daarmee de bodemstructuur.  
4. De neutrale grond die door kalk wordt veroorzaakt, stimuleert ook de stikstofbinding en daarmee de groei van niet-vlinderbloemigen. Zo neemt dus de aanvoer van organische stof en wortels toe, die een betere bodemstructuur geven en meer voer voor het bodemleven opleveren, wat ook weer bijdraagt aan de bodemstructuur.  
**IJzer**Onder luchtarme, gereduceerde omstandigheden wordt driewaardig ijzer omgezet in tweewaardig ijzer. Dit is beter oplosbaar en soms kan ijzervergiftiging optreden. Dit is evenwel zeldzaam. IJzergebrek komt vaker voor. Het kan optreden bij een hoge pH-waarde op kalkrijke gronden.  
**Mangaan**Op zure gronden met een laag organischestofgehalte kan mangaanvergiftiging optreden. Op kalkrijke gronden met een hoog organischestofgehalte is mangaangebrek mogelijk. Bekalking kan mangaanvergiftiging voorkómen. Mangaangebrek moet anders worden aangepakt. In noodgevallen is een bladbespuiting met een 1% mangaansulfaatoplossing mogelijk. Bemesting is vaak weinig succesvol bij een mangaangebrek. Op kalkhoudende zware klei met een hoog organisch stofgehalte in West-Nederland was het de gewoonte om drie jaar oude stalmest te gebruiken bij mangaangebrek. Mineralisatie van organisch gebonden mangaan speelt hierbij mogelijk een rol.Hoewel op zure gronden niet snel mangaangebrek optreedt, kan dit bij veenkoloniale gronden met veel eenzijdige humus met een hoog C/N quotiënt wel optreden. Deze humus bindt mangaan zeer sterk. De veenkoloniale haverziekte werd veroorzaakt door mangaangebrek (grijze vlekken op het blad).  
**Borium**In gesteenten is het prachtige toermalijn de belangrijkste bron van borium, maar deze halfedelsteen hebben we niet veel in de meeste bodems. Borium komt veel voor in zeewater en daarmee ook in zeekleigronden. Op boriumarme zure zandgronden kan bekalken tot boriumgebrek leiden. Bemesten met borium moet zeer zorgvuldig gebeuren. Een goede groei bij bieten en luzerne na boriumgebrek kan bij minder boriumbehoeftige gewassen tot boriumvergiftiging leiden.  
**Zink**Zinksulfaat is in gesteenten het belangrijkste zinkhoudende mineraal. Na verwering kan zinkcarbonaat, zinkhydroxide en zinkfosfaat gevormd worden. Deze zijn zeer slecht oplosbaar. Op gronden met een hoge pH treedt daarom het vaakst zinkgebrek op. In Nederland treedt zinkgebrek op in de fruitteelt bij veel fosfaat (zeer oude bewoningsplaatsen), kalk en veen in de ondergrond.Net als bij mangaan treedt zinkgebrek eerder op bij veel organische stof in de bodem.  
**Koper**Ook kopergebrek treedt eerder op bij hoge organische stofgehaltes. De ontginningsziekte deed zich voor op ontgonnen, venige heide. De jonge bladeren van granen knikten om. Bij gras is voldoende koper van belang in verband met de gezondheid van het vee. De meeste bodems onder gras leveren te weinig koper voor een goede veevoedingskwaliteit.Op arme zandgronden onder bos komt kopergebrek voor bij onder meer Douglas.Bij teveel koper, in het verleden door gebruik van Bordeauxse pap, treedt ijzergebrek op.  
**Molybdeen**De meeste sporenelementen op zure gronden zijn beter oplosbaar dan op basische, maar bij molybdeen ligt dit anders. De vorming van ijzermolybdaat, dat slecht oplosbaar is, speelt hierbij een rol. Bekalken is dan de oplossing bij molybdeengebrek.De biologische stikstofbinding is op de wereld de belangrijkste stikstofbron voor landbouwgewassen. Molybdeen speelt hierbij een belangrijke rol. Zowel bij symbiotisch levende micro-organismen als bij vrij levende, is molybdeen belangrijk bij de stikstofbinding (reductie van stikstof). Ook bij de reductie van nitraat in de plant speelt molybdeen een rol.  
Vooral op basische gronden moet zeer voorzichtig met molybdeenbemesting worden omgegaan. Bij te hoge gehalten kunnen gezondheidsproblemen met het vee ontstaan.


