---
title: 'Economische kanten van verbetering van de bodemvruchtbaarheid'
date: 2023-10-28
author: Jan Bokhorst
---


 Alle maatregelen in de landbouw die op de bodem gericht zijn kosten geld en kunnen ook geld opleveren. Dat laatste is soms op korte en soms op langere termijn. Het is per bedrijfstype en bodemtype steeds weer wat anders. Dat maakt dat het een ingewikkeld onderwerp is. In het volgende enkele voorbeelden.


**INHOUD**  

- **Economische aspecten gebruik compost**
- **Economie bodemonderhoud grasland**
- **Economie bodemonderhoud akkerbouw**
- **Economische aspecten gebruik compost**

Een gangbare akkerbouwer kan 55 euro per ha verdienen door GFT-compost te gebruiken.  

Gebruik van GFT-compost naast drijfmest en aanvullend kunstmest op een gemiddeld akkerbouwbedrijf in Zuid Nederland resulteert in een positief saldo van gemiddeld €55 ha-1 ten opzichte van de basissituatie waarin de maximaal toegelaten hoeveelheid drijfmest en kunstmest wordt gebruikt. Ook indien rekening gehouden wordt met tijdseffecten voordat meeropbrengsten en besparing op beregeningskosten worden gerealiseerd is het gemiddeld rendement over 30 jaar 17%. Het prijsverschil (op land) tussen compost en drijfmest heeft zeer grote invloed op deze bedrijfseconomische gevolgen. Indien dit verschil €9 is, in plaats van de veronderstelde €15 (in geval van GFT-compost), dan verdubbelt het positieve saldo bij compostgebruik en halveert de terugverdientijd naar 3 jaar. Dit grote effect van het prijsverschil tussen compost en drijfmest is er ook verantwoordelijk voor dat het gebruik van (dure) zeer schone compost vrijwel nooit rendabel zal zijn voor situaties waarin drijfmestgebruik een realiteit is. Ook het gebruik van compost op grasland is hierdoor zelden rendabel. Daarnaast is het effect op de gewasproductie van grote invloed op de bedrijfseconomische gevolgen van compostgebruik. Het is aannemelijk gemaakt dat de veronderstelde 5% meeropbrengst bij gebruik van GFT-compost een voorzichtige aanname is voor situaties waarin het organischestofgehalte van wezenlijke invloed is op de bodemkwaliteit. Mocht deze meeropbrengst echter lager liggen, dan daalt het bedrijfseconomisch rendement zeer snel; bij 4% meeropbrengsten bijvoorbeeld resteert een positief saldo van €21 ha-1 en daalt het gemiddeld rendement over 30 jaar naar 3%. Bron: J. de Wit, Bedrijfseconomische aspecten van compostgebruik in de akkerbouw. Louis Bolk Instituut 2013.  
  
**Economie bodemonderhoud grasland**

Door een goede verhouding te kiezen tussen blijvend gras, grasklaver en mais kan een veehouderijbedrijf op zand 7000 euro verdienen.  
 Door elke drie jaar 20% grasklaver op het melkveebedrijf te roteren met 20% snijmais, en 60% van het perceel te reserveren voor blijvend grasland met een lage frequentie van graslandvernieuwing verbetert de bodemkwaliteit aanzienlijk. Bij onderzoek van het Louis Bolk Instituut in 2016 werden het organische stofgehalte, de bodemchemie, de bodemstructuur, de beworteling, het bodemleven en de waterhuishouding beoordeelt. Zo loopt bijvoorbeeld het organische stofgehalte op dekzandgrond onder blijvend grasland op naar 6 tot 7% terwijl continue bouwland rond de 2% schommelt. Met een vruchtwisseling van 3 jaar grasklaver en 3 jaar mais kan dit organische stofgehalte oplopen naar 3,5 tot 4%. Vervolgens hebben de onderzoekers in twee scenario's doorberekend wat de effecten zijn als een gemiddeld melkveebedrijf uit de regio Achterhoek en Liemers overstapt op blijvend grasland en snijmais in rotatie met grasklaver. Hieruit blijkt dat dit geld oplevert (tussen de € 6.000 en ruim €7.400) én milieuwinst: minder aanvoer van soja en minder gebruik van kunstmest, waardoor de nitraatuitspoeling daalt, en de ammoniakuitstoot beperkt blijft. Bron: van Eekeren e.a. Veefocus december 2016.Economie bodemonderhoud akkerbouwFinanciele aspecten van bodembeheer in de akkerbouw.  
  
**Economie bodemonderhoud akkerbouw**

Aan de hand van drie cases worden de economische effecten behandeld van verbetering van de bodemkwaliteit door extra aanvoer van organische stof. Daartoe zijn voor elk van de drie cases twee bemestingsstrategieën toegepast. Van deze strategieën zijn de technische en financiële effecten op korte en lange termijn in kaart gebracht. Daartoe is gebruik gemaakt van Ndicea (model om de nutriëntenvoorziening te berekenen), GSA (LEI spelsimulatie akkerbouw om de financiële en technische resultaten op korte termijn te berekenen) en de expertise van Coen ter Berg (voor de technische effecten op lange termijn).BemestingsstrategieënDe toegepaste bemestingsstrategieën zijn ‘gewasbemesting’ en ‘bodembemesting’.Onder gewasbemesting verstaan we een bemestingsstrategie waarbij de toediening van de nutriënten zoveel mogelijk aansluit bij de behoefte van het gewas. Er wordt veel gewerkt met minerale stikstofmeststoffen door gebruik te maken van kunstmest (in gangbare landbouwsystemen) of ‘scherpe’ meststoffen zoals runderdrijfmest, kippenstrooiselmest en vinasse die in het voorjaar worden toegediend (in biologische landbouwsystemen).Bij ‘bodembemesting’ wordt het gewas indirect bemest via het bodemleven. Jaarlijks wordt een grote hoeveelheid organische stof aan de bodem toegevoegd, waarbij via allerlei bodemprocessen mineralisatie van organisch gebonden stikstof plaatsvindt. Deze stikstof kan vervolgens ten goede komen aan de plant.  
**Drie cases**Case I is een bedrijf op kleigrond met een vierjaarlijks vruchtwisselingschema met consumptieaardappelen, suikerbieten, wintertarwe, zomergerst en zaaiuien. De bedrijfsvoering is gangbaar. Voor deze case zijn twee (extreme) bemestingstrategieën toegepast. In geval van gewasbemesting worden alleen kunstmeststoffen toegediend. Bij bodembemesting is de bemesting er op gericht zoveel mogelijk organische stof aan de bodem toe te voegen door gebruik van dierlijke mest, groencompost en groenbemesting.  
Case II is een bedrijf met een biologische bedrijfsvoering. Het bedrijf ligt op zavelgrond en kent een zevenjaarlijkse vruchtwisseling met zomertarwe, consumptieaardappelen, kroten, zaaiuien en witlofwortelen. De gewasbemesting gaat uit van voorjaarsbemesting met runderdrijfmest, kippenstrooiselmest en vinasse. In het geval van bodembemesting wordt gebruik gemaakt van potstalmest in combinatie met groenbemesting, onderploegen van stroresten en het opnemen van luzerne in het bouwplan.  
Case III tenslotte is eveneens een biologisch akkerbouwbedrijf. Het ligt op kleigrond. Het bouwplan is zesjarig met zomertarwe, consumptieaardappelen, stamslabonen, suikerbieten en knolselderij. De bemestingsstrategieën zijn vergelijkbaar met Case II: De gewasbemesting bestaat uit runderdrijfmest en kippenstrooiselmest die in het voorjaar worden gegeven; de bodembemesting gaat uit van potstalmest, groencompost, groenbemesters, stroresten en luzerne in het bouwplan.  

**Resultaten op korte termijn**

In alle drie cases blijkt op korte termijn ‘gewasbemesting’ veel voordelen te hebben boven ‘bodembemesting’.Op het gangbare bedrijf (case I) zijn dat een gemakkelijke toediening, goede beschikbaarheid van de meststoffen, eenvoudige opslag, de goede voorspelbaarheid van de werking van de meststoffen en de onafhankelijkheid van de weersomstandigheden.  
Voor de beide cases met biologische bedrijfsvoering (II en III) zijn de voordelen van gewasbemesting een goede beschikbaarheid van de gebruikte relatief goedkope mestsoorten, lage uitrijkosten, geen kosten voor groenbemesting en goede gewasopbrengsten. Dit resulteert in een fors hoger saldo bij gewasbemesting; het verschil met bodembemesting is becijferd op enkele honderden euro’s per hectare. Er kleven op korte termijn ook nadelen aan gewasbemesting op biologische bedrijven. Die hebben vooral te maken met het toedieningstijdstip. In het voorjaar is men afhankelijker van weersomstandigheden, waardoor structuurschade kan ontstaan en de kans op uitstel van zaai- of pootdata groter wordt. Verder worden er hogere eisen aan de logistiek gesteld om de mest op het juiste tijdstip op de juiste locatie te krijgen. Een ander nadeel is de hogere arbeidspiek in het voorjaar.  

**Resultaten op lange termijn**

Een groot nadeel van gewasbemesting is de negatieve organische stofbalans. Jaarlijks wordt meer organische stof afgebroken dan via de bemesting wordt toegediend. Op korte termijn merk je daar niet veel van, maar op langere termijn echter breekt de negatieve organische stofbalans op. Op het gangbare bedrijf uit het teruglopende organische stofgehalte zich in een slechtere bodemstructuur, waardoor de bewerkbaarheid en de slempgevoeligheid toenemen. De opkomst van de bieten en de uien zal sterk gaan wisselen en de onkruiddruk zal toe gaan nemen. Bij bodembemesting neemt de organische stofbalans toe, waardoor de bodem beter bewerkbaar wordt, de opkomst stabieler en de onkruiddruk geringer. Dit uit zich op het gangbare bedrijf in (nog) betere financiële resultaten op lange termijn.  
Op biologische bedrijven doen deze tendensen zich ook voor. De gevolgen daarvan zijn zelfs nog groter omdat er minder correctiemogelijkheden beschikbaar zijn. Ondanks het grote financiële nadeel op korte termijn blijkt bodembemesting op langere termijn voordelen te hebben.  

**Kosten van afzonderlijke bodemverbeterende maatregelen**

Er is een globale inschatting gemaakt van de kosten van verschillende manieren om het organische stofgehalte op te krikken. Per ton effectieve organische stof variëren deze kosten tussen -€50 tot +€60 voor de gangbare landbouw en -€40 tot +€90 voor de biologische landbouw. In het algemeen zijn dierlijke meststoffen goedkoper dan groenbemesters, stroresten en groencompost, maar de verschillen zijn sterk afhankelijk van incidentele prijsniveaus.  
**Conclusie**Voor het gangbare bedrijf heeft een ruime organische stofvoorziening al op korte termijn een financieel voordeel bij een gunstige prijs van dierlijke mest. Op langere termijn neemt dat voordeel toe door de positieve effecten van een hoog organisch stofgehalte.  
Voor de beide biologische cases is op korte termijn gewasbemesting sterk in het voordeel, maar op langere termijn levert bodembemesting voordelen op. Over de effecten op langere termijn zijn weinig tot geen onderzoeksresultaten beschikbaar. Daarom zijn er grove aannames gemaakt over die effecten. Volgens ruwe inschattingen is de terugverdientijd van de investering in de bodemstructuur twaalf jaar (case II) tot ruim zeventien jaar (case III).  
Deze studie is tot stand gekomen in een samenwerking tussen LEI (Henri Prins), Coen ter Berg Advies en LBI (Jan Bokhorst).  
   



