---
title: 'ANDERS KIJKEN'
date: 2023-10-28
author: Jan Bokhorst
---

# ANDERS KIJKEN

---

**Anders kijken**[**Anders kijken?**](anders-kijken-naar-bodems.html#Anderskijkenapr2019)

**Bodem en stoffen**[**Stikstof en koolstof**](bodem-en-stoffen.html#cenn)[**Fosfor**](bodem-en-stoffen.html#fos)[**Kalium**](bodem-en-stoffen.html#kal)[**Magnesium**](bodem-en-stoffen.html#mag)[**Zwavel**](bodem-en-stoffen.html#zwavel)[**Zuurstof**](bodem-en-stoffen.html#zuurst)[**Zuur en basisch**](bodem-en-stoffen.html#zuur)
 
 **Bodem en plant**
 **[Vlinderbloemigen](bodem-en-plant.html#vlbl)**
 **[Kruisbloemigen](bodem-en-plant.html#kruisbl)**
 **[Granen en grassen](bodem-en-plant.html#graangras)**
 **Bodem en dier**


**Bodem en mens**
**[Bodem, mens en landschap](bodem-en-mens.html#bmla)****[Bodems vroeger en nu](bodem-en-mens.html#vroegerennu)****[Bodem en religie](bodem-en-mens.html#religie)****[Beken, rivieren, mensen](bodem-en-mens.html#moldau)****[Het riviertje de Reest](bodem-en-mens.html#reest)**

Bodem en landschap  
**[Zeekleigronden](bodem-en-landschap.html#h1)**
**[Hogere rivierkleigronden](bodem-en-landschap.html#h2x)**
**[Veengronden](bodem-en-landschap.html#h3)**
**[Zware kalkloze kleigronden](bodem-en-landschap.html#h4)****[Podzolgronden](bodem-en-landschap.html#h5)**
**[Enkeerdgronden](bodem-en-landschap.html#h6)**
**[Zandgronden in beekdalen](bodem-en-landschap.html#h7)**
**[Veenkolonien](bodem-en-landschap.html#h8)**
**[Loess en oude rivierklei](bodem-en-landschap.html#n9)**
 **Bodem en opvoeding**
 **[De wortelkindertjes](sibyle-von-olfers-de-wortellkindertjes.html#Wortelkindert)**
 **[De regenworm](jan-ligthart-de-regenworm.html#Regenworm)**
 **Bodem en biodynamisch**[Biodynamische landbouw en bodem](bodem-en-biodynamisch.html#bdenbodem)[Resultaten](bodem-en-biodynamisch.html#result2)[biodynamische bedrijven](bodem-en-biodynamisch.html#result2)  

  


