---
title: Goed bodem beheer - by Jan Bokhorst †
---


Jan Bokhorst † hield 2 websites bij met informatie over bodembeheer op janbokhorst.nl en goedbodembeheer.nl.
Deze repository is een kopie van deze informatie, in het geval de website zelf op enig moment ophoudt te bestaan.
Mogelijk een plek om met de community verder te bouwen op zijn ideeën.

- [Goed bodembeheer](goedbodembeheer)
- [Jan Bokhorst](janbokhorst)

## In memoriam Jan Bokhorst: onderzoeker en pionier
Source: [louisbolk.nl](https://www.louisbolk.nl/actueel/memoriam-jan-bokhorst-onderzoeker-en-pionier)

Sneller dan verwacht is onze oud-medewerker Jan Bokhorst overleden. Jan was medeoprichter van de afdeling landbouw binnen het Louis Bolk Instituut, die hij samen met Maarten van Tienhoven in 1977 startte.

In het veld, uitgerust met een spade, was Jan op zijn best. Hij duidde nauwkeurig wat hij waarnam in de omgeving en in de profielkuil. Zoals hij zelf aangaf: ‘De grote variëteit aan bodemanalyses en de vaak slechte onderbouwing van beoordeling en advies vormen een obstakel voor goed bodembeheer. Cijfers zonder context scheppen verwarring, hetgeen zelden leidt tot duurzaam bodembeheer.’ Zijn unieke benadering, zijn ervaring en zijn kennis vormde een inspiratie voor velen. Zijn werkwijze van bodembeoordeling heeft zich inmiddels over het hele land verspreid. In verschillende uitgaven zoals Bodem onder het landschap, Bodemsignalen en Handboek Mest en Compost is zijn kennis en aanpak als bodemkundige zichtbaar en toegankelijk geworden. Ook vulde hij zijn website goed bodembeheer met veel informatie, kennis beschikbaar stellen voor iedereen was zijn adagium.

Als onderzoeker bodem en bemesting was hij een drijvende kracht achter de ontwikkeling van de biologisch-dynamische en biologische landbouw. Goed waarnemen en relativeren met een vleug humor was zijn kunde. Ook toen Jan al met pensioen was, kon iedereen bij hem te rade.
