---
title: 'Beieren biogas'
date: 2023-10-28
author: Jan Bokhorst
---

Duits onderzoek naar de invloed van restproducten van de biogasproductie op de bodem laat zien dat dat de restproducten het bodemleven stimuleren, maar het organische stofgehalte niet op peil kunnen houden. Restproducten hebben minder voedsel voor regenwormen dan niet gefermenteerde drijfmest. Deze drijfmest stimuleert regenwormen het sterkst. 


Onderzoek naar de duurzaamheid op lange termijn van biogas restproducten

 

Uitvoerenden:

Het Instituut voor Agro-ecologie, Biologische Landbouw en Bodembescherming (IAB) en de afdeling Kwaliteitsborging en Onderzoek (AQU) van het Beierse Staatsonderzoekscentrum voor Landbouw (LfL) aan de TFZ en op Bureau voor Voedsel, Landbouw en Bossen Ansbach (AELF AN) voerde tussen 2009 en 2019 veldproeven uit met verschillende bemestingsregimes.

 

Doel

Het doel van het tienjarige experiment is het onderzoeken van de effecten van de restproducten van fermentatie van snijmaïs en tarwe op de bodem.

 

Methode

In de tienjarige veldproeven op vier Beierse locaties worden verschillende mestvarianten: digestaat, runderdrijfmest, minerale bemesting en het afvoeren van stro vergeleken op hun effect op bodemstructuur, humusgehalte en bodemorganismen.

 

Resultaten

- Organische bemesting (stro, digestaat, drijfmest) heeft een fundamenteel positief effect op alle onderzochte bodemeigenschappen
- Digestaatbemesting vertoont geen negatieve effecten op de aggregaatstabiliteit en de infiltratieprestaties van de bodem.
- De diversiteit van de bodemmesofauna wordt niet verminderd door digestaatbemesting.
- Regenwormen worden bevorderd door organische bemesting.
- De variant met runderdrijfmest vertoont echter de significant hoogste regenwormenpopulatie vanwege de hoeveelheid en energie-inhoud van de organische stof
- Op basis van de hoeveelheid toegepaste organische stof draagt digestaat meer bij aan de humusaanvoer dan ongegiste vloeibare mest.
- Bij de intensieve vruchtwisseling, zoals in het Beierse experiment met fermentatieresiduen, is de teruggave van organische mest mogelijk niet voldoende om een evenwichtige humusbalans te bereiken. Aanvullende maatregelen zoals humusverhogende gewassen, tussengewassen of ondergewassen zijn daarom noodzakelijk.

 

Extra informatie:

TFZ rapport 67: Fermentatie residu test Bavaria - Onderzoek naar de duurzaamheid op lange termijn van de biogas- en BtL 

[Home](beieren-biogas.html#dm)  





