---
title: 'biodivers boeren'
date: 2023-10-28
author: Jan Bokhorst
---

Er is veel maatschappelijke draagkracht voor een veerkrachtiger, natuurlijker landbouwsysteem. Boeren willen blijven boeren, burgers willen een betere connectie met de natuurlijke omgeving en consumenten willen een gezondere leefstijl. Biologisch, natuurinclusief, kringlooplandbouw, circulair, agro-ecologie - welk label er ook aangehangen wordt, een integrale aanpak is nodig om deze omslag in de landbouw te kunnen realiseren. Zowel burger, boer als business dragen verantwoordelijkheid om deze omslag te maken.  
Een goede biodiversiteit is de basis van een gezond agrarisch bedrijf en een gezonde landbouwsector. Die biodiversiteit vormt een essentieel onderdeel van de langetermijnvisie vanuit de overheid die de landbouw in Nederland binnen de kwaliteit van de leefomgeving met oog voor de bodem een lange termijn economisch perspectief biedt.  
Biodivers boeren brengt deze elementen samen. Het legt de nadruk op de functionaliteit van agro-ecologie, hoe een agrarisch bedrijf baat kan hebben bij verschillende agro-ecologische maatregelen en welke keuzes een boer van nu kan maken en welke ingrepen het overwegen waard zijn. Het boek is gebouwd op drie pijlers. 

Allereerst wordt duidelijk gemaakt hoezeer een gezonde bodem ten grondslag ligt aan elke biodiverse aanpak, daar ligt de kiem van een veerkrachtige bedrijfsvoering. In twee aparte, praktische hoofdstukken worden de akkerbouwsector en melkveehouderij vanuit dit natuurinclusieve perspectief belicht.  
Als tweede belangrijke poot belichten de auteurs de zo dringend nodige regionale aanpak, zodat een boerenbedrijf ingebed is in versterkende landschapselementen.  
Ten derde beschrijft Biodivers boeren de invloed van de agrobusiness, de concurrentie en de rol van de overheid en hoe we los moeten komen van mechanismes van de afgelopen vijftig jaar.  

Wat de auteurs misschien wel het allermeest duidelijk maken is dat alleen in een mix van deze drie pijlers vooruitgang in een biodivers landbouwsysteem geboekt kan worden.  
Dit boek is geschikt voor boeren in opleiding, ondernemers in het boerenbedrijf, landschapsspecialisten, maar ook voor bestuurders, beleidsontwikkelaars en opiniemakers een zeer verhelderend boek.

### Literatuur

Jan Willem Erisman Rosemarie Slobbe; Clubgroen; Nederlands Paperback 9789062240487 Druk: 1 november 2019; 192 pagina's

