---
title: 'Bodem en klimaat'
date: 2023-10-28
author: Jan Bokhorst
---

De bodem is belangrijk in het kader van de klimaatproblematiek. Het gaat dan niet zozeer om veel koolstof in de grond in te brengen, maar vooral om de bodemkwaliteit te verbeteren

Vaak wordt gedacht dat koolstof afkomstig van plantenresten in de grond brengen belangrijk is in het kader van de klimaatproblematiek. Men vergeet dan dat de ingebrachte koolstof door het bodemleven weer wordt omgezet in koolzuur en in de atmosfeer terugkomt. Hierdoor is op wat langere termijn gezien het effect veel lager dan vaak wordt aangenomen.

Waarom koolstof in de grond brengen niet zo veel kan bijdragen

- Wanneer je organische stof in de bodem brengt wordt het dus door het bodemleven weer afgebroken en komt de koolzuur weer in de atmosfeer terecht. Na ca. 40 jaar is alle koolstof die in de grond is gebracht weer in de atmosfeer.  

Kijk maar eens naar bossen in natuurgebieden waar al duizenden jaren blad en dode wortels in de grond komen. In de bodems onder die bossen bevindt zich niet zoveel koolstof. Aleen onder heel natte omstandigheden is dat anders en krijg je een dikke laag veen.

  


- Wanneer je een nieuw teeltplan bedenkt met meer gewassen die veel organische stof in de bodem brengen zoals meer granen en grassen en je gebruikt regelmatig compost en dat hou je vele jaren vol dan is dat toch maar een eenmalige actie.

Je brengt bijvoorbeeld ieder jaar twee keer zoveel koolstof in de grond. Die hoeveelheid moet je na 10 jaar door 10 delen, na 100 jaar door 100 en op lange termijn wordt de bijdrage dus steeds lager. De koolstof die via menselijke activiteiten in de atmosfeer komt is niet eenmalig, maar gaat jaar in jaar uit door.

Wat wel kan bijdragen: minder koolstof in de vorm van koolzuur naar de atmosfeer laten ontsnappen

- Nu komt bodemvruchtbaarheid om de hoek kijken. Bodemvruchtbaarheid betekent een hogere opbrengst en een hogere meststofefficiëntie. Bij bodemvruchtbaarheid gaat het niet in eerste instantie om veel koolstof in de grond te brengen. Het gaat om een evenwicht in aanvoer van stikstofrijk en koolstofrijk voer voor het bodemleven.

Bijvoorbeeld:

gras/klaver. Je hebt koolstofrijke graswortels, stikstofrijke klaver en het resultaat is veel wormen en stikstof die geen fossiele brandstof nog had.

of 

drijfmest (stikstofrijk) in de nazomer op een koolstofrijke groenbemester uitbrengen.

of

stalmest gebruiken: mengsel van stikstofrijke mest en koolstofrijk stro). 

Let op:

  


Veel organische stof in de bodem betekent ook veel stikstof in de organische stof (stikstof is energie bij kunstmest of landoppervlakte bij vlinderbloemigenteelt) en veel fosfor in de organische stof (fosforschaarste). De verhouding C:N:P in organische stof is ca 100:10:1)

  


Wat nog meer doen

  


Koolstof onder de bewerkte laag inbrengen – Niet kerende grondbewerking – De hele keten aanpakken (ca 25% van de koolzuuruitstoot van de menselijke activiteit op de wereld komt van de voedselproductie; slechts 30% van deze 25% komt van de teelt zelf) – vertering van veen beperken - enz. enz. 


  


Het Parijse akkoord

  


Er is al eerder op gewezen dat er een fout in het Parijse akkoord zit. Ieder jaar 0,4% organische stof erbij. Ook hier lijkt vergeten dat er organische stof afgebroken wordt. Vergelijk het met een emmer met een gat erin. Je doet iedere keer een bepaalde hoeveelheid water in de emmer en er ontstaat een bepaald niveau. Nu wil je een hoger niveau. Dan moet je meer water steeds in de emmer doen, maar er komt een nieuw vast niveau. Wanneer je jaarlijks meer organische stof wilt hebben dan moet je jaarlijks meer geven en op een gegeven moment is er geen ruimte meer voor voedselproductie. Bij de bodem is het gat in de emmer de afbraak van organische stof door het bodemleven.   


Wat kan wel

Is het effect op lange termijn van extra koolstof de grond inwerken zeer gering, op kortere termijn kan er een duidelijker effect zijn. Een studie die van 2019 tot 2023 loopt (Koopmans e.a., 2020) geeft, aan de hand van meerjarige proefvelden, aan welke eventuele mogelijkheden er wel zijn. Bij akkerland gaat het dan bij de studie om evaluatie van 25% meer graan en meer mest en compost. Bij grasland om minder vaak opnieuw inzaaien.


De resultaten voor de eerste 30 jaar na invoering van een nieuwe maatregel:  

  

| Nummer | Maatregel | ton CO2/ ha/ per jaar |
| --- | --- | --- |
| 1 | NKG akkerbouw | 0 |
| 2 | Meer graan akkerbouw | 1,6 |
| 3 | Mest of compost akkerbouw | 0,5 |
| 4 | mais na gras | 0 - 2,5 |
| 5 | minder herinzaai gras | 0 - 5,5 |


Toelichting

- Niet Kerende Grondbewerking (NKG) verhoogt het koolstofgehalte niet. Een van de redenen kan zijn dat door ploegen de koolstof wat dieper wordt ingewerkt waardoor deze minder snel wordt afgebroken.
- 25 % meer graan in het bouwplan geeft meer koolstof in de grond. Toepassing van deze maatregel  is niet altijd makkelijk omdat graan financieel niet aantrekkelijk is.
- Toepassing van mest en compost geeft koolstofopslag. De remmende factor is nu de fosfaatwetgeving. De meeste bedrijven hebben nu geen ruimte om meer fosfaat te geven.
- Niet continu mais telen maar afwisselen met gras. Op zware klei in Friesland geeft dit en duidelijk effect (2,5 ton CO2 per ha per jaar). Op zand was er geen verschil aan te tonen. Dit komt mogelijk door de hogere organische stofgehalten op zandgrond die een eventueel verschil moeilijker laten zien.
- Minder herinzaai.  Op zware klei in Friesland een duidelijk effect, op zand geen duidelijk effect..

  


## Literatuur

Muller, e.a., 2016. Organic farming, climate change mitigation and beyond. www.ifoam-eu.org.

Berge, H. ten e.a.. 2017. Research for Agri Committee. Preserving agricultural soils in the EU. 

http://www.europarl.europa.eu/committees/en/supporting-analyses-search.html 

Minasny, B. e.a., 2017. Soil carbon 4 per mille. Geoderma, Vol 292, p 59-86. https://doi.org/10.1016/j. geoderma.2017.01.002

Koopmans, C.J., e.a. 2020. Evaluatie van maatregelen voor het vastleggen van koolstof in minerale gronden 2019-2023. Voortgangsreportage april 2020. Ministerie van LNV.  Den Haag.


  




