---
title: 'Bodem na droogte'
date: 2023-10-28
author: Jan Bokhorst
---

# Bodem na droogte



---






        **Het bodemleven na droogte**

Schimmels en bacteriën zijn van het kleine bodemleven de belangrijkste groepen.  Droogt de grond uit dan kunnen schimmels daar vrij goed tegen. Bacteriën  hebben meer poreuze celwanden en drogen uit. Ze gaan dood, gaan over in een latente toestand of vormen snel sporen voor later. Wanneer door regen de bodem weer vochtig wordt gebeurt er van alles. De latente uitgedroogde bacteriën nemen vocht op en worden weer actief, maar een deel neemt zoveel vocht op dat ze dan alsnog dood gaan. De levende bacteriën kunnen nu de dode als voedsel gebruiken. Ze hebben om in leven te blijven veel koolhydraten  als energiebron nodig en ook eiwitten worden als energiebron gebruikt. Voor de opbouw van de eigen lichaamssubstantie is niet zoveel stikstofrijk eiwit nodig. Wanneer een levende bacterie een dode eet blijft er dus van alles over: voedingsstoffen zoals stikstof (ammonium en nitraat) en fosfaat. Hiervan kunnen planten groeien. De sterke groei van planten na droogte komt dus niet alleen door het vocht, maar ook door de vrijkomende voedingsstoffen. Er is nog iets anders dat de sterke groei verklaart. Wortels scheiden wortelexudaten uit. Dat is een mengsel van koolstofhoudende verbindingen, eiwitten, aminozuren en suikers. Deze stimuleren de groei van micro-organismen, ook van die micro-organismen die voedingsstoffen voor de plant vrijmaken. Na droogte worden er meer wortelexudaten uitgescheiden dan onder normale omstandigheden. Het bacterieleven rond de wortel (microbioom)  wordt zo sneller hersteld. Onderzoeker Francisca de Vries van de UVA deed veel onderzoek naar droogte en bodemleven.   

  

[Home](index.htm#dm)
  










