---
title: 'bodemstructuur 2020'
date: 2023-10-28
author: Jan Bokhorst
---

# bodemstructuur 2020

---


        **De bodemstructuur in het voorjaar van 2020**  
Door de vele regen staat dit voorjaar vaak water onder in de bouwvoor. Ook in de bouwvoor is de structuur door de vele regen vaak slecht. Na de lange natte periode kwam een zeer droge periode. De grond werd keihard waardoor de bodembewerking moeilijk is. Opvallend is de vaak zeer mooie grond onder groenbemesters.   
  
  
Wat te doen  
-Bewerk de bodem wanneer dat maar even mogelijk is. Bij verder uitdrogen wordt de bewerking lastiger.  
-Zijn er veel grove kluiten dan bij vroege gewassen als ui en aardappel nog even wachten. Het beste is wachten op regen. Beregenen werkt minder goed dan regen.-Bij niet Phytophthora resistente aardappelrassen toch wel vroeg poten. De ruggen daarna snel frezen.-Bij grond die te hard is voor een zaaibedcombinatie een kopeg of hakenfrees gebruiken.-Pas op dat nog levende groenbemesters niet teveel vocht onttrekken. Snel onderwerken.-Stap eventueel van het plan af om te gaan ploegen of woelen.-Zaai niet in een grof zaaibed. Gebruik eventueel kluitenruimers of een schoffel met aanaarder.-Na zaai moet de grond vochtig blijven, maar niet te snel na zaai beregenen vanwege kans op verslemping.-Bij te losse grond rollen, maar niet wanneer zware regen verwacht wordt.  
Maximale zoutwaarden beregeningswater-Zaaiui, peen, sla, klaver, erwt en boon de bovengrens ergens rond een EC 1-Rode biet en spinazie ergens een bovengrens rond de EC 2-Plantuien een bovengrens van rond EC 2,5-Aardappel, knolselderij en kool een bovengrens van EC 3-Granen bovengrens EC 4  
Bron: naturim.nl  
[Home](index.htm#dm)  


