---
title: 'Bodem en ziektewerendheid'
date: 2023-10-28
author: Jan Bokhorst
---

# Bodem en ziektewerendheid

---


        Bodem en ziektewerendheid
=========================

 De weerstand van de bodem tegen ziekten en plagen zorgt ervoor dat een gewas niet direct ziek wordt zodra er een ziekteverwekker in de bodem opduikt. Bodemweerbaarheid ontstaat door de biologische activiteit in de bodem, maar ook de chemische en fysische gesteldheid van de bodem spelen een rol. Weerstand van de bodem tegen ziekten en plagen wordt ook wel ziektewerendheid (soil suppressiveness) genoemd en is het verschijnsel waarbij de ontwikkeling van ziekten minimaal is, zelfs in de aanwezigheid van een virulent pathogeen en een vatbare gastheer (Baker & Cook, 1974; Cook & Baker, 1983; Mazolla, 2002; Schlatter et al., 2017).   
Het bestaan van ziektewerende bodems is al meer dan 100 jaar bekend en de mechanismen waarmee ziektesuppressie tot stand wordt gebracht, wordt al bijna vier decennia bestudeerd (Baker & Cook, 1974; Cook & Baker, 1983; Mazolla, 2002; Schlatter et al., 2017). Door een samenspel van biotische en abiotische factoren blijft zelfs bij aanwezigheid van schadeverwekkers de opbrengstderving op ziektewerende bodems beperkt (Mazzola, 2002). Er wordt verondersteld dat natuurlijke (biodiverse) bodems een algemene (of ‘natuurlijke’) weerstand tegen bodempathogenen kennen. Een grote biodiversiteit van bodemflora en -fauna die de voortplanting van bodempathogenen afremt, zou een mogelijke verklaring zijn.   
Er zijn twee vormen van ziektewerendheid: (1) algemene ziektewerendheid en (2) specifieke ziektewerendheid (Mazzola, 2002). Algemene ziektewerendheid komt voort uit de diversiteit en activiteit van het bodemleven (Mazzola, 2002; Cook, 2014; Schlatter et al., 2017). Door onderlinge concurrentie om ruimte en voedingsstoffen wordt uitbreiding van schadelijke organismen afgeremd en is de omvang van een aantasting geringer dan in een steriele grond (Mazzola, 2002). Voor algemene ziektewerendheid is geen specifiek organisme aan te wijzen dat ten grondslag ligt aan de verminderde schadegevoeligheid, maar spelen meerdere factoren een rol (Mazzola, 2002; Schlatter et al., 2017). Bij specifieke ziektewerendheid gaat het om een beperkt aantal antagonisten (“een gunstig organisme”) dat in staat is één of een aantal schadeverwekkers in een bepaald gewas in toom te houden bijvoorbeeld via predatie of door het uitscheiden van antibiotica. Deze specifieke ziektewerendheid is in principe zowel stuurbaar als overdraagbaar, mits we het mechanisme van dit beperkt aantal antagonisten in de complexe omgeving begrijpen (Weller et al., 2002; Schlatter et al., 2017).   
Een voorbeeld van ziektewerende bodems in de Nederlandse vollegrond is bijv. de continue teelt van bloemkool welke de infectie van Rhizoctonia solani onderdrukt doordat er een opbouw van antagonisten optreedt gedurende de tijd (Postma & Schilder, 2005).   
De natuurlijke onderdrukking van zo’n ziekteverwekkende bodemschimmels wordt dus vooral bepaald door de activiteit en de samenstelling van de microben in de bodem. Deze activiteiten zijn goed te sturen door goed bodembeheer met organische meststoffen, zoals groenbemesters of compost (Cook, 2014; Schlatter et al., 2017). De timing van het bemesten is dan wel belangrijk wat betekent dat de microben in de bodem de makkelijk afbreekbare onderdelen van de meststoffen al op hebben op het tijdstip dat de gewassen gezaaid of gepoot worden (Brussaard et al., 2016). Op hetzelfde moment scheiden de jonge planten ook voedingsstoffen uit via de wortels voor de microben waardoor de bodem vol zit met microben die geen schade doen aan het gewas. De ziekteverwekkers krijgen op dat moment minder kans om een infectieproces op gang te brengen.   
Naast het toevoegen van organische meststoffen kan een agrarische ondernemer of veredelaar ook kiezen voor planten die de weerbaarheid van de bodem verhogen door de zogenoemde wortelexudaten (Brussaard et al., 2016). Wortelexudaten bevatten componenten die worden gebruikt in strategieën voor ondergrondse communicatie, zoals flavonoïden, strigolactonen of terpenoïden (Bais et al., 2006; Venturi & Fuqua, 2013; Jacoby et al., 2017; Massalha et al., 2017). Bepaalde wortelexudaten worden door de plant uitgescheiden waardoor bijvoorbeeld ziekte-onderdrukkende microben worden gestimuleerd. We hebben hier nog wel veel te leren waarbij vooral gebruik gemaakt zou kunnen worden van de wilde verwanten van bepaalde gewassen (Brussaard et al., 2016).     
*Bron: **Inaugurele rede J. van de Mortel HAS Hogeschool Venlo 2019**.  De gehele inaugurele rede kunt u [hier](../files/Lang%20leve%20de%20bodem%20-%20Judith%20van%20de%20Mortel%20-%202019.pdf) 
lezen. Blijf op de hoogte van actuele projecten en voortgang van het lectoraat -Gezonde plant op een duurzame en vitale bodem- via de [website van het lectoraat](https://has.nl/nl/lectoraten/gezonde-plant-op-vitale-duurzame-bodem).*  


