---
title: 'De geur na regen'
date: 2023-10-28
author: Jan Bokhorst
---

# De geur na regen



---






        **De geur na regen**
Wanneer het in de zomer na een droge periode regent ruiken we een typische geur. Bijna iedereen vindt die geur heel  aangenaam.  David Brown zegt (The Times 8 april 2020): Deze geur leidt tot gevoelens van hoop en vernieuwing. Dat de geur positief door de mens wordt gewaardeerd gaat samen met het feit dat het na wat langere droogte weer regent. De stof waar het om gaat is geosmin. Afgeleid van het Griekse aarde en geur. De stof wordt ook wel petrichor genoemd. De menselijke neus is er extreem gevoelig voor. 1 ppb is al te ruiken. Dat is veel minder dan wat een haai nodig heeft om bloed te ruiken. In de bodem zijn het springstaarten die direct op de geur van geosmin af gaan. Noorse en Zweedse onderzoekers van het John Innes instituut ontdekten dit recent.  De springstaarten vinden via de geur van geosmin de bacteriën die de geosmin produceren (streptomyceten). Ze verspreiden zo de sporen van de bacteriën en de bacteriën zelf net zoals bijen het stuifmeel van bloemen verspreiden.     
Geosmine komt ook in rode biet voor en geeft rauwe rode biet de typische smaak. Het kan ook drinkwater, wijn en andere voedingsstoffen een grondsmaak geven. Vissen die in water leven waar blauwalgen die geosmin produceren in voorkomen smaken er ook naar. Paling met grondsmaak is bij palingliefhebbers berucht. 
  

N.N. GERBER, H.A. LECHEVALIER. "Geosmin, an Earthy-Smelling Substance Isolated from Actinomycetes." Applied Microbiology (1965), vol. 13 nr. 6, pp. 935-938.  

JIAOYANG JIANG, XIAOFEI HE, DAVID E. CANE. "Geosmin Biosynthesis. Streptomyces coelicolor Germacradienol/Germacrene D Synthase Converts Farnesyl Diphosphate to Geosmin." J. Am. Chem. Soc. (2006), vol. 128 nr. 25, pp. 8128-8129. DOI:10.1021/ja062669x
M.T. LISANTI, P. PIOMBINO, A. GAMBUTI, A. GENOVESE, L. MOIO. "Earthy off-flavour in wine: evaluation of remedial treatments for geosmin contamination." Food Chemistry (2014), vol. 154, pp. 171-178. DOI:10.1016/j.foodchem.2013.12.100
[Home](index.htm#dm)
  










