---
title: 'Enquête: Boeren kijken te weinig naar de bodemstructuur'
date: 2023-10-28
author: Jan Bokhorst
---

Bodemverdichting is een belangrijk probleem. De meeste boeren hebben dat niet in de gaten.  
Het blad Akkerwijzer doet verslag van een Agrio-enquête bij 59 loonbedrijven over de werkwijze van boeren rond het probleem van bodemverdichting.  
Bijna 3 van de 4 loonwerkers zeiden dat boeren te weinig geld uitgeven aan vermindering van bodemverdichting.  

**Everhard van Essen** van adviesbureau Equator Groen & Ruimte zei hierover dat dit komt omdat er te weinig naar de grond wordt gekeken. Men gebruikt wel bredere banden, maar de machine wordt ook vaak zwaarder en dan werkt het niet. 

**Frank Verhoeven** van agrarisch adviesbureau Boerenverstand vind dat boeren bezuinigen op verkeerde zaken. Ca. 60 % kijkt te veel naar de korte termijn. Meer aandacht is nodig voor de langere termijn: bodem en goed veevoer van eigen land.Meer informatie in het artikel van zaterdag 31 augustus 2019 in de regiobladen Agraaf, Stal & Akker, Vee & Gewas, Veldpost en Akkerwijzer.nl.  
  


