---
title: 'Kiss the ground'
date: 2023-10-28
author: Jan Bokhorst
---

# Kiss the ground

---


        De op zich indrukwekkende film kan bij mensen die totaal niets van de bodem afweten ertoe leiden dat voor hen de bodem en het begrip bodemvruchtbaarheid in beeld komt. Er wordt evenwel veel onzin over de bodem gezegd. Het gevaar bestaat dat voorstanders van een industrielandbouw, met veel kunstmest en gif, het gevoel krijgen dat alternatieve ideeën op drijfzand zijn gebouwd en dat je er geen aandacht aan hoeft te besteden.

     


Enkele voorbeelden van onjuistheden in de teksten

  


-De bodem kan gigantisch veel koolstof opslaan. (Dat kan bij veengronden met zeer hoge grondwaterstanden. In de landbouw is de meeste koolstof die je als plantenresten in de bodem stopt na 30 tot 50 jaar weer als koolzuur terug in de atmosfeer. Je best wel wat doen aan koolstofopslag: Grassen granen telen, groenbemesters, minder grondbewerking enz. In de veehouderij het scheuren van gras beperken).


  


-Zonder planten meer verdamping dan met planten op de bodem (Dat is net andersom).

  


-2/3 deel van de wereld is aan het verwoestijnen. (Woestijnen ontstaan alleen in een extreem droog deel van de wereld).

  


-IS en migratie naar Europa vanuit Afrika komt door slecht bodembeheer (Bodem is slechts een onderdeel van het probleem).

  


-Door bewerken van de bodem in februari en maart komt er in die periode veel koolzuur in de lucht (Het bodemleven moet dat doen. In februari en maart is het te koud voor het bodemleven).

  


-De koolstof die in de bodem gebracht wordt kan daar eeuwen blijven. (Dat geldt voor een heel klein deel. De rest is na ca 40 jaar alweer in de atmosfeer door omzetting door het bodemleven).

  


-Anders boeren geeft na 20 jaar de benodigde klimaatverandering op de hele wereld (De winst die te halen is per bedrijfstype verschillend maar vaak toch beperkt. Je kunt niet alle koolstof in de bodem stoppen; je moet ook nog voedsel telen).


  


-Cop Parijs 2015: verhoging van het organische stofgehalte met 0,4% ieder jaar compenseert alle koolzuur van de hele wereld (Ook hier wordt ervan uitgegaan dat er geen organische stofafbraak door het bodemleven is. Dat de VS, India en China niet tekenden is  heel jammer maar te begrijpen).

  


-Voedselbossen hebben hogere opbrengst per ha. (Dat is niet waar).

  


Bij bewerkte grond gaat veel water over de oppervlakte naar de sloot (geldt soms, maar in het algemeen niet).

  


Enz.



