---
title: 'Maatregelen akkerbouw'
date: 2023-10-28
author: Jan Bokhorst
---

# Maatregelen akkerbouw



---






        

 ### maatregelenakkerbouw




   Maatregelen in het kort in alfabetische volgorde.

  
Dit overzicht komt uit de publicatie ‘Van bodembeoordeling naar acties’ van Coen ter Berg.

  


De volledige publicatie is te downloaden via
[www.cosunleden.nl](http://www.cosunleden.nl/) / Unitip / Handleiding bodemconditie

  


De volgende onderwerpen worden behandeld:

  


-Bekalken

-Bodemleven stimuleren

-Bouwplan intensief

-Drainage

-Egalisatie

-Groenbemesters

-Groenbemesters onder dekvrucht

-Grondbewerking

-Grondbewerking kerend

-Infiltratie

-Mechanisatie

-Onderwerken groenbemesters

-Ontwatering

-Organische stof

-Organische bemesting

-Rijpaden

-Vruchtopvolging

-Woelen  
-Wortelduizendpoot





   ﻿﻿  


W﻿at zie je



 ﻿﻿  


W﻿aar op letten



 ﻿﻿  


Hoe uitvoeren

﻿﻿  






    BEKALKEN
========






   -pH-KCl of pH-CaCl2  lager dan 6,5

-Slechte vertering van gewasresten en organische bemesting

-Matige structuur op klei en lössgronden

-Laag poriënvolume


-Weinig wormenactiviteitNieuwe alinea



 -Bodemanalyse: pH en CEC bezetting van Ca

-Vertering organisch materiaal

-Poriënvolume


-Wormenactiviteit

-StructuurNieuwe alinea



 -Bij een lage pH is een reparatie bekalking nodig. Streeftraject van akker/tuinbouw op klei ligt tussen 6 en 7

-Bij pH voldoende en Ca gehalte laag, regelmatig bekalken met een kleine gift in het najaar- Gips of landbouwkalk?


-Gips CaSo4: verhoogd de pH niet en is vooral geschikt voor structuurverbetrering op klei- en lössgronden Beoordeel eerst de bodemconditie!

-Kalk CaCo3: is pH verhogend, verbetert de structuur en stimuleert het bodemleven


-Gebruik kalk regelmatig en met mate

-Reparatie bekalking om de pH te verhogen: Verhoog de pH geleidelijk met jaarlijks een kleine gift (300-500kg/ha)

-Onderhouds bekalking om de bodemprocessen te verbeteren: kom regelmatig met een jaarlijkse kleine gift (200-300kg





    BODEMLEVEN STIMULEREN
=====================






   -Laag poriënvolume

-Slechte vertering van gewasresten en organische bemesting

-Weinig wormenactiviteit

-Verslempte bovengrond

-Matige structuur > 30% scherpblokkig

  




 -Bouwplan en vruchtopvolging- Aandeel groenbemesters, rust- en diepwortelende gewassen

-Organische bemesting en verdeling in vruchtopvolging

-Activiteit van bodemleven (poriën en agregaatvorming)

  




 -Meer (vlinderbloemige) groenbemesters telen

-Meer rustgewassen telen en stro onderwerken

-Goede verdeling organische bemesting in bouwvoor

-Verbeter C:N bij de organische bemesting en org. stof aanvoer

-Ploegen zonder voorschaar

-Ondieper ploegen of spitten

-pH naar streefwaarde

-Regelmatig bekalken met kleine gift

-Bemesten met vaste stalmest

-Structuur verbeteren

-Waterhuishouding verbeteren





    BOUWPLAN INTENSIEF
==================






   -Afname bodemstructuur-

-Weinig stabiele aggregaten op lichte zavel -

en zandgronden-

-Afname bodemleven-


-Toename bodemgebonden ziekten

-Afname productie en productkwaliteit

  




 -Aandeel rustgewasen

-Aandeel laatrooiende gewassen

-Plantgezondheid

-Productkwaliteit

  




 -Aandeel rustgewassen verhogen: b.v. 1 op 3 pootgoed met 2 jaar tarwe + stro en groenbemesters

-Aandeel vroegrooiende gewassen verhogen t.b.v. meer groenbemesters: w.gerst, tulp, plantui etc.

-Input organische meststoffen verhogen (benut fosfaatruimte voor org. bemesting)

-Bodemleven stimuleren







    DRAINAGE
========






   -Grondwaterpeil regelmatig boven 60 cm onder maaiveld

-Plasvorming die niet binnen 24 uur weg is

-Lage draagkracht

-Roestvorming in wortelzone

-Wortelsterfte en wortelrot

-Afname bodemleven door regelmatige waterverzadiging

  




 -Plaats peilbuizen om grondwaterstand te volgen

-Worden de eindbuizen ieder jaar schoon gemaakt

-Leeftijd en functie bestaande drainage- Bepaal of drainage beter is dan oppervlakkige waterafvoer

  




 -Bij homogene klei- lössprofielen met doorgaande beworteling en poriën tot dieper dan 60 cm kan sleufloos gedraineerd worden

-Bij gelaagde profielopbouw waarin wortelgroei geremd wordt en slecht doorlatende lagen aanwezig zijn kan beter met kettingmachine gewerkt worden

-Bij profielen met een slecht doorlatende zone met een dikte van meer dan 30 cm is het gebruik van drainagezand in de sleuf aan te bevelen

-Laagten kunnen apart en intensiever gedraineerd worden door dwars op de bestaande drains, extra sleuven met drainage zand aan te leggen

-Drainafstand gemiddeld 6 meter. Bij goed ontwaterende profielen kan ruimer gedraineerd worden

-Omhulling: gemiddeld pp700

  






    EGALISATIE
==========






   -Ongelijke ligging

-Ingesloten laagten waardoor plasvorming

-Hoog opgeploegde kanten

  




 -Bepaal de noodzaak voor bolle of vlakke ligging

-Breng de hoogteverschillen van het perceel in kaart: GPS (ahn)

-Bepaal hoeveel en waar het meeste geschoven moet worden

-Bepaal de dikte van de humusrijke en vruchtbare laag

-Bepaal de kwaliteit van de ondergrond

  




 -Voer de egalisatie onder droge omstandigheden uit

-Ploeg of spit alleen de humusrijke laag

-Vermijd menging met humusarme grond, veen en onrijpe klei met de humusrijke toplaag

-Streef naar een minimale humusrijke toplaag van 25 cm

-Bij veel grondverzet en te dunne humusrijke bovengrond: Zet dan eerst de humusrijke toplaag opzij, egaliseer de ondergrond en breng de humusrijke toplaag weer terug

-Woel na het egaliseren tot 40 cm diepte om de verdichting door het egaliseren op te heffen- Bemest of bekalk na het egaliseren

-Zaai direct na het woelen een diepwortelende groenbemester of tarwe in

  






    GROENBEMESTERS
==============






   -Vastleggen voedingsstoffen

-Vermindering uitspoeling

-Opbouw organische stof

-Voeding bodemleven

-Bodembedekking

-Structuurbehoud en verbetering

-Diversiteit plantenfamilies in bouwplan

-Onkruidonderdrukking

  




 -Bemesting

-Zaaitijdstip

-Bodembewerking

-C:N

-Wortelintensiteit en diepte

-Stikstof binding

-Aaltjes besmetting

-Plantfamilie

-Vorstgevoeligheid

  




 -Het resultaat hangt af van tijdstip van zaaien, de lengte van de groeiperiode

-Een dag groei in augustus is een week groei in september

-Vroeg zaaitijdstip: voor half augustus: alle groenbemesters


-Laat zaaitijdstip: na half augustus: haver, tarwe, rogge, gras, wikken, bladrammenas en mosterd

-Zeer late zaai: na half sept: rogge, gras, haver

-Hoe hoger de bemesting hoe groter het gewas bovengronds en hoe kleiner het wortelstelsel

-Bemest groenbemesters weinig of niet

-Ploeg de groenbemester onder zonder voorschaar

-Verdeel de groenbemester bij het onderwerken in de laag van 0 tot 20 cm

-Organische stof opbouw en sterke doorworteling: grassen, granen, luzerne, rode klaver

-Vanggewas en snelle ontwikkeling: kruisbloemigen, facelia, haver

-Stikstofbinding en bodemleven stimuleren: vlinderbloemigen

-Mengsels kunnen de diversiteit aan plantenfamilies verhogen. De bemestingstoestand bepaald welke soort in het mengsel zich het sterkst ontwikkeld

-Haver en wikken: de wikken binden stikstof en bevordert de groei van haver en daarmee de koolstofopbouw

- Aaltjesbestrijding: afrikaantjes en raketblad





    GROENBEMESTERS ONDER DEKVRUCHT
==============================






   Verlenging groeiperiode

Bespaard grondbewerking



 Bepaal lengte en groeiverwachting dekvrucht



 -Voer eerst de onkruidbestrijding in de dekvrucht voldoende uit

-Zaai 14 dagen voor de dekvrucht sluit

-Rol het gezaaide aan bij droogte

-Kies geen breedbladige en sterk bodembedekkende dekvrucht of ras

-Bemest de dekvrucht niet te zwaar





    GRONDBEWERKING
==============






   -Cultivator

-Schijveneg

-Bouwvoorlichter

-Woeler



 -Timing

-Vlakligging

-Inzet groenbemesters

-Bewerkingsdiepte

-Onkruidontwikkeling en bestrijding



 -NKG houdt meer vocht vast: alleen werken onder voldoende droge omstandigheden

-Bodemleven neemt een deel van het werk over: bewerk de bodem alleen waar nodig

-Keuze groenbemesters op bodembedekking en vorstgevoeligheid

-Onkruidbeheersing en hergroei groenbemesters

-Combineer NKG met rijpadensysteem





    GRONDBEWERKING KEREND
=====================






   -Ploegen

-Ekoploegen

-Spitten



 -Ploegdiepte

-Gebruik en afstelling voorschaar

-Onderwerken gewasresten en groenbemesters



 -Voorkom ploegzool: rij bovenover of onder droge omstandigheden

-Werk groenbemesters niet in 1 laag in de ondergrond: gebruik geen voorschaar

-Verdeel organisch materiaal door de bouwvoor: spitten of voorbewerken met schijveneg

-Ploeg, spit geen humusarme ondergrond naar boven

-Houdt een vaste ploegdiepte aan

-Ploeg niet dieper dan 25 cm en bij voorkeur rond 20 cm

-Ploeg, spit zware kleigronden direct na de oogst﻿





    INFILTRATIE
===========






   -Slootpeil hoog zetten tijdens droge periode



 -Kwaliteit water  
 -Hoogte grondwater in het perceel

-Bewortelingsdiepte gewas  
 -Slempgevoeligheid in profiel

  




 -Gebruik geen stilstaand water met veel algen groei

-Bij slempgevoelige profielen niet langdurig onder water zetten

-Zorg dat het grondwater niet hoger komt dan 60 cm onder maaiveld

-Zorg voor een snelle en tijdige waterafvoer bij weersomslag

-Bewerk de bodem of oogst pas wanneer het vochtgehalte voldoende is afgenomen in de laag 0-50 cm﻿





    MECHANISATIE
============






   -Spoorvorming  
 Structuurbederf

  




 -Keuze machinepark  
 -Bandenkeuze en bandenspanning  
 -Breng eigen mechanisatie en bandendruk in kaart  
 -Ontwatering

  




 -Voorkom structuurbederf door goede ontwatering

-Timing: werk onder droge bodemomstandigheden

-Streefwaarde bandenspanning: Voorjaar 0,4 bar. Najaar 0,8 bar

-Investeringsplanning: betere banden onder huidige mechanisatie

﻿- Keuze loonwerker

  






    ONDERWERKEN GROENBEMESTERS
==========================






   -Verkrijgen van schoon, zaaiklaar land﻿  
 -Opname en vertering door het bodemleven  




 -Menging door de bouwvoor  
 -Diepte onderwerken

  




 -Verdeel de groenbemester homogeen door de laag 0 tot 20 cm

-Voorkom ophoping van organisch materiaal in de ondergrond

-Ploegen zonder voorschaar

-Voorbewerking met een schijveneg en direct daarna ploegen

-Ondiep < 20 cm ploegen kan met voorschaar

-Spitten

-Bij NKG kies voor groenbemesters die makkelijk afvriezen of weinig hergroei hebben

-Vorstgevoelige groenbemesters: facelia, mosterd, afrikaantjes, boekweit en raketblad- Groenbemesters met weinig hergroei: facelia, mosterd, rogge﻿





    ONTWATERING
===========






   -Plasvorming die langer blijft staan dan 24 uur

-Roestvorming in de wortelzone

-Water blijft staan op ondergrond (verdichte laag)

-Verdichte laag

  




 -Zomer en winterpeil

-Waterbergend vermogen: poriënvolume

-Ontwaterend vermogen in het profiel


(poriën, wortelgangen, storende zand en veenlagen)

-Vlak, bol ligging of ingesloten laagten

-Plaats peilbuizen om grondwaterpeil te volgen﻿﻿  




 -Egalisatie

-Onderhoud drainage

Aanleg nieuwe drainage

-Opheffen storende laag

  






    ORGANISCHE STOF
===============






   -Lage gehalten

-Matige tot slechte structuur

-Weinig activiteit van het bodemleven

-Laag poriënvolume

  




 -pH, O.S.% en C:N

-Bodemleven activiteit

-Bodemstructuur

-Beworteling

-Waterhuishouding

-Organische stof balans

  




 -Meer groenbemesters

-Meer granen en grassen in vruchtopvolging

-Minder intensieve bodembewerking

-Minder diep ploegen of spitten

-Bekalk bij te lage pH en/of te weinig activiteit van het bodemleven

-Bekalk regelmatig met kleine giften (200-300 kg) in de herfst

-Verbeter de ontwatering

-Verbeter de structuur

-Stimuleer het bodemleven met regelmatige aanvoer van vaste stalmest

-Verhoog het organische stof gehalte met compost

-Bevorder de wortelontwikkeling door goede ontsluiting naar de ondergrond (structuur en waterhuishouding)﻿





    ORGANISCHE BEMESTING
====================






   -Vaste stalmest﻿  
 -Drijfmest﻿  
 -Compost﻿  
 -Groenbemesting



 -Beoordeel kwaliteit als meststof 

(mineralengehalten)

-Beoordeel kwaliteit bodemverbetering


(org. stof, stimulering bodemleven, C:N)

-Beoordeel kwaliteit op vervuiling

-Rijpheid van stalmest en compost

-Beoordeel groenbemesters op familie, bijdrage wortels en bodemleven

  




 -Gebruik drijfmest hoofdzakelijk als minerale plantenvoeding (voorjaar)

-Drijfmest kan via de ontwikkeling van een groenbemester bodemvoedend worden

-Vaste stalmest soorten bevorderen vooral wormen, ander bodemleven en bodemstructuur

-Compost bevordert hoofdzakelijk het org. stof gehalte, bodemstructuur en microbieel bodemleven- Gebruik goed gerijpte compostsoorten


-Vermijd vervuilde en te heet geworden compostsoorten


-Zet groenbemesters doelgericht in





    RIJPADEN
========






   -Om onbereden teelbedden te realiseren

-Eerder bewerken en zaaien in het voorjaar

-Toepassen in combinatie met NKG, spitten, ondiep ploegen

-Ontstaan van sterk verdichte sporen﻿



 -Afstemming van alle werkzaamheden op GPS



  -Oogst is nog niet goed ontwikkeld op rijpaden

-Dwars op de bedden ploegen om sporen op te heffen

  






    VRUCHTOPVOLGING
===============






   -Afname productie door te nauwe rotatie

-Afname bodemstructuur door groot aandeel laatrooiende gewassen

-Afname bodemstructuur door te intensieve bewerking (rugopbouw en zeefkettingen)

-Te weinig bodemleven activiteit


-Te weinig aanvoer van organische stof en voeding bodemleven

-Afname plantgezondheid en productkwaliteit﻿



 -Beoordeel opbouw en afname bodem conditie in de tijd

-% rustgewassen

-% diepwortelende gewassen

-% bodemvoedende gewassen

-Afwisseling en frequentie plantfamilies

-Afwisseling maai en rooigewassen

-Opbouw organische stof

  




 -Vormt basis van de bodemconditie

-Voldoende rustgewassen


-Voldoende diep wortelende gewassen

-Voldoende aanvoer gewasresten (organische stof opbouw)

-Afstemming frequentie plantfamilies  
 -Bodemleven voeding (vlinderbloemigen en makkelijk afbreekbare organische stof)

  






    WOELEN
======






   -Ploegzool  
 -Storende laag

  


  




 -Bepaal het poriënvolume in de storende laag  
 -Bepaal de mate van verstoring op beworteling en waterhuishouding  
 -Bepaal noodzaak van woelen

﻿

  




 -Hoe dieper in de bodem hoe meer het herstellend vermogen afneemt

-Wanneer er voldoende poriën zijn in de verdichte laag, woel dan niet

-Alleen woelen wanneer er een duidelijke verstoring van de waterhuishouding of beworteling is

-Woel alleen de laag die nodig is

-Woel niet wanneer er geen gewas staat

-Woel onder droge omstandigheden op de woeldiepte

-Woel bij voorkeur in een grasgroenbemester die al flink ontwikkeld is (circa 15 cm hoogte)﻿





    WORTELDUIZENDPOOT
=================






   Wortels van fijnzadige gewassen worden opgegeten (ui, suikerbiet, biet en peen)

  


  


  


  


  


  


De tekst over de wortelduizendpoot is ontleent aan C. den Herder en L. Janmaat in Ekoland: Wortelduizendpoot,  december 2021



 -Zijn er scheuren (bij zware klei) of poriën en gangen die naar diepere lagen gaan.  
-is er veel grof organisch materiaal bijvoorbeeld uit vaste mest.

--Wordt er niet kerende grondbewerking toegepast. Deze kan meer hinder geven

  




 -Verdeel het organische materiaal goed door de bouwvoor  
-Teel geen ui na gras-klaver  
-Zaai groenbemesters wat later  
-Werk groenbemesters tijdig in   
-Zaai ondiep zodat planten snel aan de groei gaan  
-Streef naar een wat vaster zaaibed met minder gangen door rollen voor of na zaai  
-Waarschijnlijk helpt een periode met braak aan het eind van de teelt in het vorige jaar  
-Stop met niet kerende grondbewerking wanneer de plaag aanhoudt

-Ploeg organisch materiaal voldoende diep onder in de herfst  
-Geef geen mest voor het inzaaien  






  


  


  







