---
title: 'PUBLICATIES'
date: 2023-10-28
author: Jan Bokhorst
---


**Bestanden om vrij te downloaden**    

### WERKEN AAN BODEMVRUCHTBAARHEID


In ruim 100 pagina's een praktijkgids over maatregelen om bodems te verzorgen. Nieuwe publicatie met veel actuele informatie. Gericht op akkerbouw, tuinbouw en grasland, oktober 2021.

[Download Werken aan Bodemvruchtbaarheid](../files/Werken%20aan%20bodemvruchtbaarheid%20okt%202021.pdf)


### BODEMVRUCHTBAARHEID PER BODEMTYPE


De belangrijkste aandachtspunten per bodemtype met vele voorbeelden uit de praktijk. Een uniek overzicht over de verschillen in aanpak.


[Bodemvruchtbaarheid per bodemtype 6 mb](../files/bodemvruchtbaarheid_per_bodemtype.pdf)


### DIAGNOSIS OF SOIL RELATED CROP PROBLEMS

Overzicht over bodembeheer in de biologische landbouw,  
Gerard Oomen [Download het document 4 mb](../files/diagnosis%20soil%20related%20crop%20problems%20%202020%20%281%29.pdf)


### DE KOOLSTOF-STIKSTOFDYNAMIEK

Bij bodembeheer gaat het er niet in de eerste plaats om veel koolstofhoudende organische stof in de grond te brengen. Ook verteerbare stikstofhoudende organische stof is nodig. Worden beide tegelijk aangeboden dan maakt het bodemleven de bodem vruchtbaar.  
[De koolstof-stikstofdynamiek 2 mb](../files/koolstof_stikstof_dynamiek.pdf)

### STOFFEN IN DE BODEM

Je kunt beter met voedingsstoffen voor planten omgaan wanneer je ze beter kent.  
[Stoffen in de bodem 2,5 mb](../files/stoffen_in_de_bodem.pdf)

### OERNATUUR IS OVERAL

Bij iedere bodem hoort een specifieke natuur. De natuur is krachtig en laat overal de oorspronkelijke natuur zien. Je ziet het als je vanuit de bodem kijkt.


[Oernatuur is overal 7 mb](../files/oernatuur_is_overal.pdf)



### BODEMS VAN DE WERELD

Een overzicht van de belangrijkste bodems van de wereld die voor voedselproductie in gebruik zijn met per bodemtype de aandachtspunten waar de boer aan moet werken en de wijze waarop hij dat kan doen.


[Bodems van de wereld 3 mb](../files/bodems_van_de_wereld.pdf)



### PRODUCTKWALITEIT

Een handleiding om niet alleen gericht op kilogrammen te telen, maar ook op smaak en gezondheid. Bodembeheer en raskeuze staan centraal.   
[Productkwaliteit 4 mb](../files/productkwaliteit.pdf)

### BODEM ONDER HET LANDSCHAP

De betekenis van de bodem voor landschap, landbouw en natuur. Nu in hardcover. Het boek is verkrijgbaar in de boekhandel, bij Bol.com en bij de uitgever Roodbont.nl.


[Bekijk een hoofdstuk uit het boek](../files/Hoofdstuk%20uit%20Bodem%20onder%20het%20landschap.pdf)



