---
title: 'Structuurverbeterende middelen'
date: 2023-10-28
author: Jan Bokhorst
---

Veel middelen zijn soms wel heel goed, maar vaak toch niet. Dat speelt al heel lang in de landbouw. Handelaren van middelen willen graag verkopen, dat is ze niet kwalijk te nemen. Zelf goed opletten of een middel het goede middel op de juiste plaats is, is belangrijk. Het vraagstuk begon al met kunstmest, maar gaat, met steeds nieuwe middelen, nog steeds door. 


Veel middelen zijn soms wel heel goed, maar vaak toch niet. Dat speelt al heel lang in de landbouw. Handelaren van middelen willen graag verkopen, dat is ze niet kwalijk te nemen. Zelf goed opletten of een middel het goede middel op de juiste plaats is, is belangrijk. Het vraagstuk begon al met kunstmest, maar gaat, met steeds nieuwe middelen, nog steeds door.   
Organische stof toedienen in verteerbare vorm is het beste middel om de bodemstructuur te verbeteren, maar lukt onder de huidige omstandigheden vaak niet voldoende.  
Een oud middel om een slechte bodemstructuur te verbeteren is schuimaarde. De werking is voornamelijk fysisch; de invloed op de zuurgraad en stimulering van het bodemleven is beperkt. De losse brokken schuimaarde gaan de verdichting tegen.  
De vele problemen met de bodemstructuur hebben tot gevolg gehad dat er veel middelen op de markt worden gebracht die de bodemstructuur zouden verbeteren. 

**In 2010 is door PPO en NMI een onderzoek gestart** 

naar de werking van een aantal middelen. Hoewel van de meeste getoetste middelen al bekend is dat ze niet werken, is het toch goed dat dit onderzoek plaats vindt omdat het veel onzekerheid bij de akkerbouwers weg kan nemen.  
De plaatsten waar proeven liggen zijn:  
PPO Vredepeel (dalgrond)PPO Vathermond (dalgrond)PPO Westmaas (Zuidwestelijk kleigebied)PPO Lelystad (Centraal kleigebied)SPNA-Kollumerwaard (Noordelijk kleigebied)  
De middelen die getoetst worden zijn:  

**Agrigyps**

Agrigyps is gips met 29 procent CaO. Gips beinvloedt de pH niet . Toediening is 1700 kg Agrigyps per ha. De vele zwavel in het product kan een probleem zijn in verband met toekomstige wetgeving met betrekking tot zwavel in het oppervlaktewater.  

**Betacal Carbo**

Betacal Carbo is de klassieke schuimaarde. Het is een neerslag van kalk gemengd met enige organische stof die is ontstaan bij de zuivering van ruwsap uit bieten. Het bevat ook wat stikstof, fosfaat en kalium. Het wordt als volgt toegepast:2010 1000 kg CaO per ha in voorjaar en in dat najaar 500 kg CaO per ha.De daarop volgende jaren: in voorjaar 500 kg CaO per ha.  

**Brandkalk**

Dit is gebluste kalk met 60% CaO en tot 35% MgO. Met Brandkalk wordt de hoeveelheid vrij calcium en de magnesiumvoorziening in de bouwvoor verhoogd. Brandkalk is licht pH verhogend, maar is geen kalkmeststof. Het kan voor een hogere Ca-bezetting van het adsorptiecomplex zorgen. Toepassing is 500 kg CaO per ha in het voorjar bij de zaai- en pootbedbereiding.  

**PRP-SOL**

PRP-SOL is verhit calciummagnesiumcarbonaat. Hieraan worden sporenelementen toegevoegd. Toediening is 200 kg per ha. De eerste twee jaar was de dosering hoger.

**Condit 7% N**

Condit bestaat uit onder meer gehydroliseerde eiwitten uit de melkbereiding en zeolieten. Het bevat 7% stikstof, 1% fosfaat en 2% kalium. Toediening van 1 ton per ha en daarmee 70 kg werkzame stikstof per ha.  

**Xurian Optimum**

Xurian Optimum is een meststof met borium, zink en een Pseudomonasbacterie. Het product wordt toegepast met een veldspuit. Het eerste jaar is de dosering 1,35 kg per ha. De jaren erna wordt 0,9 kg per ha in zomer of najaar gegeven. De toediening vindt plaats na de oogst van het gewas voor de inzaai van een groenbemester of in het najaar kort voor het ploegen op een groenbemester.  

**Biochar**

Biochar ontstaat door verhitting van biomassa onder zuurstofloze omstandigheden. Die biomassa is bermgras, snoeiafval, energiegewassen en reststromen van deverwerkende industrie. Na verhiting blijft er houtskool over dat Biochar wordt genoemd. Het materiaal kan grof of poedervormig zijn. Het idee van Biochar is afgeleid van Terra Preta, organische stofrijke (tot 16%) vruchtbare, zwarte gronden in het Amazonegebied in Brazilië, maar de verkoolde resten van de Nederlandse Biochar zijn hier niet mee te vergelijken.Toediening is 2,5 en 5 ton per ha.  

**Steenmeel**

Steenmeel is een gemalen steenachtig product van deeltjes kleiner dan 0,1 mm van vulkanische oorsprong . Toediening is 15 ton per ha. In 2010 en 2011 konden geen effecten van betekenis worden vastgesteld. Het onderzoek gaat 5 jaar duren. 2015 is het laatste jaar.**Literatuur**  
Paauw, J.G.M., 2011. Effecten van bodem- en srtructuurverbeteraars. Onderzoek op klei-, zand- en dalgron

