---
title: 'Frank Verhoeven'
date: 2023-10-28
author: Jan Bokhorst
---






De voorstellen van Frank Verhoeven:





Weidegang: meer dan 150 dagen x 20 uur. Waarom? Minder mest opvangen in de stal en minder mest uitrijden geeft minder ammoniakemissie.

Ureum: lager dan 20. Een betere afstemming tussen energie en eiwit in het rantsoen van de melkkoeien zorgt voor minder stikstof in de urine.

Stikstof van eigen land: meer dan 65%. Grondgebonden boeren: efficiënt omgaan met stikstof zoveel mogelijk van je eigen land of uit de regio.

Ammoniakemissie: minder dan 50 kg NH3 per hectare. Een optelsom van alle maatregelen in voeding, bemesting, weidegang, stalsysteem, minder jongvee, enzoverder.

Stikstof bodemoverschot: lager dan 125 kg N per hectare. De stikstof die niet de lucht in gaat, gaat verloren richting bodem en water.



Wie dit jaar in jaar uit moet betalen is nog niet geheel duidelijk, maar er moet wel wat gebeuren. "het ijzer is nu heet".



Over de financiering zegt hij:

We starten met een bedrag van 1 euro per 1.000 kg melk per indicator per jaar wat de boer kan verdienen. Dus als er aan alle vijf van de stikstofindicatoren voldaan wordt en er 800.000 kg melk wordt geleverd is er dus 4.000 euro per jaar te verdienen. Dat moet voldoende stimuleren. De regeling gaat lopen over meerdere jaren, zolang er geld in de pot blijft. En het staat de ‘groene partijen’ en belanghebbenden zoals provincies en waterschappen natuurlijk vrij de pot verder te spekken.



Over de criteria:

Waarom deze criteria? Omdat hiermee structureel en bedrijfsspecifiek de stikstofuitstoot wordt verminderd. Iedereen: intensief of extensief, groot of klein, op zand, klei of veen moet hier ergens goed op kunnen scoren. Vervolgens zoekt de boer helemaal zelf uit of hij dit met of zonder (erkende) bedrijfsadviseur gaat fiksen. Als je voldoet aan de bovenwettelijke criteria, heb je de stikstofpremie verdiend. Dit is een aanpak gericht op verleiding en met meer respect voor de boer als professionele ondernemer. Dus sector, het ijzer is nu heet: doe er je voordeel mee!



Ter toelichting:

Ureum  
Ureum is een stikstofrijke verbinding in melk. Het gehalte mag niet lager dan 15 zijn omdat de melkeiwitproductie dan geremd wordt. Waarden boven 30 duiden op veel te hoge aanvoer van stikstof in het voer. Bij weiden van koeien buiten kan het ureumgehalte sterk variëren en boven de 20 uitkomen. Bijvoeren met eiwitarm krachtvoer kan dan nodig zijn.

Stikstofbodemoverschot  
De hoeveelheid stikstof die in de bodem terechtkomt kan als ammoniak de lucht in gaan of als nitraat uitspoelen. Bij een laag organische stofgehalte is er stikstof nodig voor humusopbouw. Te overwegen is om dan een hoger stikstofoverschot toe te staan.




Lees meer op Boerenverstand.nl en het boek Bodemsignalen Grasland.  
    
 




  











