---
title: 'Virussen in de bodem'
date: 2023-10-28
author: Jan Bokhorst
---


**Virussen. Zitten die ook in de bodem?**  
  
Virussen zijn soms heel nuttig  
Virussen hebben invloed op planten, dieren en mensen. Steeds dringt een virusdeeltje een organisme binnen en laat zich daar door het organisme vermenigvuldigen. De cel waarin het gebeurt springt open en nieuwe virusdeeltjes komen vrij. Bij planten kan dit een sterk negatief effect op de groei hebben. Er zijn veel soorten virusziekten bij planten. Vaak worden de virussen verspreid door bijvoorbeeld luizen.
  
In de zee zitten ook veel virussen. In een glas zeewater gemiddeld 150 miljoen virusdeeltjes. Virussen in zeewater hebben evenwel een belangrijk positief effect. Zouden er geen virussen in zeewater zitten dan zouden veel voedingsstoffen naar de bodem van de zee verdwijnen en het oppervlaktewater zou sterk verarmen. Virussen doden bacteriën, algen en andere organismen ondiep in de zee. De virussen zijn daarom heel belangrijk voor een stoffenkringloop in het water.  
  
  
## Bodemvirussen en planten  
  
Over virussen in de bodem die landbouwgewassen aantasten is veel bekend. Van het tulpenvirus TVX is bekend dat verplaatsing in de bodem mogelijk is maar dat dat niet door een bepaald organisme gebeurt. Hoe dan wel is niet bekend. Recent is door de Proeftuin Zwaagdijk in samenwerking met de WUR aangetoond dat TVX 8 maanden in de bodem in leven kan blijven.  
  
De leliebranche wordt geconfronteerd met een zeer besmettelijk virus dat een grote bedreiging is voor de gehele leliesector, het Plantago asiatica mosaic virus (PlAMV). Naast PlAMV is enkele jaren geleden een vergelijkbaar virus in lelie aangetroffen, het Tulpenvirus X (TVX). De besmettelijkheid van TVX lijkt bij lelie vergelijkbaar groot te zijn als de besmettelijkheid van PlAMV. Vuil en plantenresten van de bollen wegspoelen met (warm) water en eventueel zeep gebruiken om aankoeken van vuiligheid te voorkomen zijn het belangrijkst en het meest effectief.De verspreiding van PlAMV en TVX is complex, de beheersing van dit virus nog complexer. Een groot aantal onkruiden en groenbemesters zijn waardplant.  
Bij sla kennen we het bobbelblad- en kringnecrosevirus. Ze worden in de bodem verspreid door de bodemschimmel Olpidium brassiae. Deze schimmel ontwikkeld zich in vochtige luchtarme grond. Zorgen voor een goede bodemstructuur is belangrijk om de schade te beperken.   
  
## Bodemvirussen en het bodemecosysteem  
  
Hebben bodemvirussen ook een belangrijke rol in het bodemecosysteem? Bekend is dat er vele soorten bodemvirussen zijn en dat ze in alle bodems van de wereld voorkomen. Ze leven van bacteriën. Zorgen ze misschien voor een sneller vrijkomen van voedingsstoffen in het voorjaar? Hier is niets over bekend. Er is nooit onderzoek gedaan naar een eventuele invloed van virussen op de bodemecologie.  

  
  


