---
title: 'het vn-ipcc rapport'
date: 2023-10-28
author: Jan Bokhorst
---

Het recente rapport van het VN klimaatpannel IPCC (Intergovernmental Panel on Climate Change) geeft aan dat de wereldvoedselvoorziening na 2050 een knelpunt wordt.   
De intensieve landbouw in veel gebieden op aarde is de oorzaak van de achteruitgang van de bodemkwaliteit en remt de voedselproductie. Verder moet de landbouw minder broeikasgassen produceren. De landbouw en ander landgebruik nemen een kwart van de broeikasgassen voor hun rekening. Landgebruik en voedingsgewoonten moeten op de schop. Alleen oproepen tot een ander beheer van bodems en een ander voedingspatroon met minder vlees zullen niet helpen. Er moeten dwingende regels komen. De conclusies van het rapport zijn gebaseerd op ruim 7000 wetenschappelijke publicaties.  

**Reacties op het rapport:**

**NRC (redactioneel) en Biologische landbouw (Bionext)**: Er ligt een belangrijke taak voor de biologische landbouw.  

**Rudy Rabbinge en Joost van Kasteren (ex WUR)**: “Alleen intensieve landbouw kan voldoende voedsel produceren”. Dit is een hele oude mening van hen. “Kies voor de beste gronden, dan heb je meer grond voor natuur”. Jammer dat ze nog steeds niet lijken te beseffen dat gronden alleen goed zijn wanneer er langere tijd aandacht voor de bodemkwaliteit is geweest. Zeer intensieve landbouw gaat altijd ten koste van de bodem.  

**Tom Saat, biologisch boer in Almere** heeft grote moeite met de negatieve visie op vlees eten (Trouw, 27-08-2019). Rundvee is via de mest van belang voor de bodemvruchtbaarheid zegt hij en er zijn veel gronden waar alleen gras kan groeien. Daar heeft hij gelijk in. Dat grasland veel koolstof kan binden ziet hij verkeerd. Wat er aan koolstof ingaat komt er ook weer uit. Er stelt zich altijd een evenwicht in. Verwaarloosd gras kan bij beter beheer wel tijdelijk veel koolstof binden.   

**Wat is er te doen**Het probleem is groot. Samenwerking vanuit de verschillende gezichtspunten is van belang. De intensieve technische landbouw vergeet bodemvruchtbaarheid. De biologische landbouw doet dat niet, maar moet hard werken aan een beter onderbouwde lange termijnvisie rond wereldvoedselvoorziening. 

