---
title: 'Voedsel uit zee'
date: 2023-10-28
author: Jan Bokhorst
---

Jaap van der Meer is onderzoeker bij het Wageningen Marine Centrum en bijzonder hoogleraar dierecologie aan de Vrije Universiteit Amsterdam. In december schreef hij een artikel in het tijdschrift Nature Food. Hij zei dat de bestaande modellen voor “Blue Growth” houden geen rekening met de beschikbaarheid van nutriënten en de opbouw van de voedselpiramide. Alleen van de oppervlakte zeewater.

Door de lage gehalten aan voedingsstoffen is de productie veel lager dan op land. Water is er natuurlijk wel, zonlicht ook en vaak ook een voldoende hoge temperatuur. Wat betreft chemische bodemvruchtbaarheid is de zee te vergelijken met een woestijn zegt van der Meer.

Op zee bestaat de meeste biomassa uit algen. Daarvan wordt 6 procent omgezet in voedsel voor planteneters. Deze planteneters bestaan uit eencellige algen en dierlijk plankton. Deze kunnen wij niet oogsten omdat eventuele netten zeer veel energie kosten om voort te slepen. We kunnen vrijwel alleen vissen. Wieren kunnen we ook niet op grotere schaal als voedsel gebruiken omdat deze zich aan de zeebodem moeten hechten en dus alleen aan kusten geoogst kunnen worden. In kustzones zou je wel kunnen bemesten maar dat gaat zeer inefficiënt en je verliest veel steeds schaarser wordend fosfor.  

Zie ook
[www.wur.nl/grenzen-voedselproductie-zee](http://www.wur.nl/grenzen-voedselproductie-zee).  










